
"""
moderntreasury

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class DocumentControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.document
        cls.response_catcher = cls.controller.http_call_back

    def test_list_documents(self):
        """
        Get a list of documents.
        """
        # Parameters for the API call
        documentable_id = None
        documentable_type = None
        after_cursor = None
        per_page = None

        # Perform the API call through the SDK function
        self.controller.list_documents(
            documentable_id,
            documentable_type,
            after_cursor,
            per_page,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "x-after-cursor": None,
            "x-per-page": None,
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

