
"""
moderntreasury

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class PaymentOrderControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.payment_order
        cls.response_catcher = cls.controller.http_call_back

    def test_create_async_payment_order(self):
        """
        Create a new payment order asynchronously.
        """
        # Parameters for the API call
        idempotency_key = None
        body = None

        # Perform the API call through the SDK function
        self.controller.create_async_payment_order(
            idempotency_key,
            body,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 202
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_list_payment_orders(self):
        """
        Get a list of all payment orders.
        """
        # Parameters for the API call
        after_cursor = None
        per_page = None
        mtype = None
        priority = None
        counterparty_id = None
        originating_account_id = None
        transaction_id = None
        status = None
        direction = None
        reference_number = None
        effective_date_start = None
        effective_date_end = None
        metadata = None

        # Perform the API call through the SDK function
        self.controller.list_payment_orders(
            after_cursor,
            per_page,
            mtype,
            priority,
            counterparty_id,
            originating_account_id,
            transaction_id,
            status,
            direction,
            reference_number,
            effective_date_start,
            effective_date_end,
            metadata,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "x-after-cursor": None,
            "x-per-page": None,
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

