
"""
moderntreasury

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class ExpectedPaymentControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.expected_payment
        cls.response_catcher = cls.controller.http_call_back

    def test_list_expected_payments(self):
        """
        List expected_payments.
        """
        # Parameters for the API call
        after_cursor = None
        per_page = None
        status = None
        internal_account_id = None
        direction = None
        mtype = None
        counterparty_id = None
        metadata = None
        created_at_lower_bound = None
        created_at_upper_bound = None

        # Perform the API call through the SDK function
        self.controller.list_expected_payments(
            after_cursor,
            per_page,
            status,
            internal_account_id,
            direction,
            mtype,
            counterparty_id,
            metadata,
            created_at_lower_bound,
            created_at_upper_bound,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "x-after-cursor": None,
            "x-per-page": None,
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_create_expected_payment(self):
        """
        Create expected payment.
        """
        # Parameters for the API call
        idempotency_key = None
        body = None

        # Perform the API call through the SDK function
        self.controller.create_expected_payment(
            idempotency_key,
            body,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 201
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

