
"""
moderntreasury

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class ReturnControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.mreturn
        cls.response_catcher = cls.controller.http_call_back

    def test_list_returns(self):
        """
        Get a list of returns.
        """
        # Parameters for the API call
        after_cursor = None
        per_page = None
        internal_account_id = None
        counterparty_id = None
        returnable_id = None
        returnable_type = None

        # Perform the API call through the SDK function
        self.controller.list_returns(
            after_cursor,
            per_page,
            internal_account_id,
            counterparty_id,
            returnable_id,
            returnable_type,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "x-after-cursor": None,
            "x-per-page": None,
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_create_return(self):
        """
        Create a return.
        """
        # Parameters for the API call
        idempotency_key = None
        body = None

        # Perform the API call through the SDK function
        self.controller.create_return(
            idempotency_key,
            body,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 201
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

