"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AccountNumberType2Enum(object):
    """Implementation of the 'AccountNumberType2' enum.

    Attributes:
        IBAN: The enum member of type str.
        CLABE: The enum member of type str.
        WALLET_ADDRESS: The enum member of type str.
        PAN: The enum member of type str.
        OTHER: The enum member of type str.

    """

    _all_values = ["iban", "clabe", "wallet_address", "pan", "other"]
    IBAN = "iban"

    CLABE = "clabe"

    WALLET_ADDRESS = "wallet_address"

    PAN = "pan"

    OTHER = "other"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
