"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class AddressRequest(object):
    """Implementation of the 'address_request' model.

    Attributes:
        line_1 (str): The model property of type str.
        line_2 (str): The model property of type str.
        locality (str): Locality or City.
        region (str): Region or State.
        postal_code (str): The postal code of the address.
        country (str): Country code conforms to [ISO 3166-1 alpha-2]
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "line_1": "line1",
        "line_2": "line2",
        "locality": "locality",
        "region": "region",
        "postal_code": "postal_code",
        "country": "country",
    }

    _optionals = [
        "line_1",
        "line_2",
        "locality",
        "region",
        "postal_code",
        "country",
    ]

    _nullables = [
        "line_1",
        "line_2",
        "locality",
        "region",
        "postal_code",
        "country",
    ]

    def __init__(
        self,
        line_1=APIHelper.SKIP,
        line_2=APIHelper.SKIP,
        locality=APIHelper.SKIP,
        region=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        country=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AddressRequest instance."""
        # Initialize members of the class
        if line_1 is not APIHelper.SKIP:
            self.line_1 = line_1
        if line_2 is not APIHelper.SKIP:
            self.line_2 = line_2
        if locality is not APIHelper.SKIP:
            self.locality = locality
        if region is not APIHelper.SKIP:
            self.region = region
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if country is not APIHelper.SKIP:
            self.country = country

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        line_1 =\
            dictionary.get("line1")\
            if "line1" in dictionary.keys()\
                else APIHelper.SKIP
        line_2 =\
            dictionary.get("line2")\
            if "line2" in dictionary.keys()\
                else APIHelper.SKIP
        locality =\
            dictionary.get("locality")\
            if "locality" in dictionary.keys()\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if "region" in dictionary.keys()\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if "postal_code" in dictionary.keys()\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if "country" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(line_1,
                   line_2,
                   locality,
                   region,
                   postal_code,
                   country,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _line_1=(
            self.line_1
            if hasattr(self, "line_1")
            else None
        )
        _line_2=(
            self.line_2
            if hasattr(self, "line_2")
            else None
        )
        _locality=(
            self.locality
            if hasattr(self, "locality")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"line_1={_line_1!r}, "
            f"line_2={_line_2!r}, "
            f"locality={_locality!r}, "
            f"region={_region!r}, "
            f"postal_code={_postal_code!r}, "
            f"country={_country!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _line_1=(
            self.line_1
            if hasattr(self, "line_1")
            else None
        )
        _line_2=(
            self.line_2
            if hasattr(self, "line_2")
            else None
        )
        _locality=(
            self.locality
            if hasattr(self, "locality")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"line_1={_line_1!s}, "
            f"line_2={_line_2!s}, "
            f"locality={_locality!s}, "
            f"region={_region!s}, "
            f"postal_code={_postal_code!s}, "
            f"country={_country!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
