"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class BalanceTypeEnum(object):
    """Implementation of the 'BalanceType' enum.

    The specific type of balance reported. One of `opening_ledger`, `closing_ledger`,
    `current_ledger`, `opening_available`, `opening_available_next_business_day`,
    `closing_available`, `current_available`, or `other`.

    Attributes:
        CLOSING_AVAILABLE: The enum member of type str.
        CLOSING_LEDGER: The enum member of type str.
        CURRENT_AVAILABLE: The enum member of type str.
        CURRENT_LEDGER: The enum member of type str.
        OPENING_AVAILABLE: The enum member of type str.
        OPENING_AVAILABLE_NEXT_BUSINESS_DAY: The enum member of type str.
        OPENING_LEDGER: The enum member of type str.
        OTHER: The enum member of type str.

    """

    CLOSING_AVAILABLE = "closing_available"

    CLOSING_LEDGER = "closing_ledger"

    CURRENT_AVAILABLE = "current_available"

    CURRENT_LEDGER = "current_ledger"

    OPENING_AVAILABLE = "opening_available"

    OPENING_AVAILABLE_NEXT_BUSINESS_DAY = "opening_available_next_business_day"

    OPENING_LEDGER = "opening_ledger"

    OTHER = "other"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
