"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class BalanceReportType1(object):
    """Implementation of the 'balance_report_type1' enum.

    Attributes:
        INTRADAY: The enum member of type str.
        OTHER: The enum member of type str.
        PREVIOUS_DAY: The enum member of type str.
        REAL_TIME: The enum member of type str.

    """

    INTRADAY = "intraday"

    OTHER = "other"

    PREVIOUS_DAY = "previous_day"

    REAL_TIME = "real_time"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
