"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Code1Enum(object):
    """Implementation of the 'Code1' enum.

    The return code. For ACH returns, this is the required ACH return code.

    Attributes:
        ENUM_901: The enum member of type str.
        ENUM_902: The enum member of type str.
        ENUM_903: The enum member of type str.
        ENUM_904: The enum member of type str.
        ENUM_905: The enum member of type str.
        ENUM_907: The enum member of type str.
        ENUM_908: The enum member of type str.
        ENUM_909: The enum member of type str.
        ENUM_910: The enum member of type str.
        ENUM_911: The enum member of type str.
        ENUM_912: The enum member of type str.
        ENUM_914: The enum member of type str.
        R01: The enum member of type str.
        R02: The enum member of type str.
        R03: The enum member of type str.
        R04: The enum member of type str.
        R05: The enum member of type str.
        R06: The enum member of type str.
        R07: The enum member of type str.
        R08: The enum member of type str.
        R09: The enum member of type str.
        R10: The enum member of type str.
        R11: The enum member of type str.
        R12: The enum member of type str.
        R14: The enum member of type str.
        R15: The enum member of type str.
        R16: The enum member of type str.
        R17: The enum member of type str.
        R20: The enum member of type str.
        R21: The enum member of type str.
        R22: The enum member of type str.
        R23: The enum member of type str.
        R24: The enum member of type str.
        R29: The enum member of type str.
        R31: The enum member of type str.
        R33: The enum member of type str.
        R37: The enum member of type str.
        R38: The enum member of type str.
        R39: The enum member of type str.
        R51: The enum member of type str.
        R52: The enum member of type str.
        R53: The enum member of type str.
        CURRENCYCLOUD: The enum member of type str.

    """

    _all_values = ["901", "902", "903", "904", "905", "907", "908", "909",
        "910", "911", "912", "914", "R01", "R02", "R03", "R04", "R05", "R06", "R07",
        "R08", "R09", "R10", "R11", "R12", "R14", "R15", "R16", "R17", "R20", "R21",
        "R22", "R23", "R24", "R29", "R31", "R33", "R37", "R38", "R39", "R51", "R52",
        "R53", "currencycloud"]
    ENUM_901 = "901"

    ENUM_902 = "902"

    ENUM_903 = "903"

    ENUM_904 = "904"

    ENUM_905 = "905"

    ENUM_907 = "907"

    ENUM_908 = "908"

    ENUM_909 = "909"

    ENUM_910 = "910"

    ENUM_911 = "911"

    ENUM_912 = "912"

    ENUM_914 = "914"

    R01 = "R01"

    R02 = "R02"

    R03 = "R03"

    R04 = "R04"

    R05 = "R05"

    R06 = "R06"

    R07 = "R07"

    R08 = "R08"

    R09 = "R09"

    R10 = "R10"

    R11 = "R11"

    R12 = "R12"

    R14 = "R14"

    R15 = "R15"

    R16 = "R16"

    R17 = "R17"

    R20 = "R20"

    R21 = "R21"

    R22 = "R22"

    R23 = "R23"

    R24 = "R24"

    R29 = "R29"

    R31 = "R31"

    R33 = "R33"

    R37 = "R37"

    R38 = "R38"

    R39 = "R39"

    R51 = "R51"

    R52 = "R52"

    R53 = "R53"

    CURRENCYCLOUD = "currencycloud"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
