"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class Connection(object):
    """Implementation of the 'connection' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        vendor_id (uuid|str): Unique identifier for the bank or vendor.
        vendor_customer_id (uuid|str): An identifier given to this connection by the
            bank.
        vendor_name (str): A human-friendly name for the bank or vendor.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "vendor_id": "vendor_id",
        "vendor_customer_id": "vendor_customer_id",
        "vendor_name": "vendor_name",
    }

    _nullables = [
        "discarded_at",
        "vendor_customer_id",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        vendor_id=None,
        vendor_customer_id=None,
        vendor_name=None):
        """Initialize a Connection instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.vendor_id = vendor_id
        self.vendor_customer_id = vendor_customer_id
        self.vendor_name = vendor_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        vendor_id =\
            dictionary.get("vendor_id")\
            if dictionary.get("vendor_id")\
                else None
        vendor_customer_id =\
            dictionary.get("vendor_customer_id")\
            if dictionary.get("vendor_customer_id")\
                else None
        vendor_name =\
            dictionary.get("vendor_name")\
            if dictionary.get("vendor_name")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   vendor_id,
                   vendor_customer_id,
                   vendor_name)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.object,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.live_mode,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.created_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.updated_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.discarded_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.vendor_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.vendor_customer_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.vendor_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("object"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("live_mode"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("created_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("updated_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("discarded_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("vendor_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("vendor_customer_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("vendor_name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _vendor_id=self.vendor_id
        _vendor_customer_id=self.vendor_customer_id
        _vendor_name=self.vendor_name
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"vendor_id={_vendor_id!r}, "
            f"vendor_customer_id={_vendor_customer_id!r}, "
            f"vendor_name={_vendor_name!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _vendor_id=self.vendor_id
        _vendor_customer_id=self.vendor_customer_id
        _vendor_name=self.vendor_name
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"vendor_id={_vendor_id!s}, "
            f"vendor_customer_id={_vendor_customer_id!s}, "
            f"vendor_name={_vendor_name!s}, "
            f")"
        )
