"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class CounterpartyCollectAccountResponse(object):
    """Implementation of the 'counterparty_collect_account_response' model.

    Attributes:
        id (str): The id of the existing counterparty.
        is_resend (bool): This field will be `true` if an email requesting account
            details has already been sent to this counterparty.
        form_link (str): This is the link to the secure Modern Treasury form. By
            default, Modern Treasury will send an email to your counterparty that
            includes a link to this form. However, if `send_email` is passed as
            `false` in the body then Modern Treasury will not send the email and you
            can send it to the counterparty directly.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "is_resend": "is_resend",
        "form_link": "form_link",
    }

    def __init__(
        self,
        id=None,
        is_resend=None,
        form_link=None):
        """Initialize a CounterpartyCollectAccountResponse instance."""
        # Initialize members of the class
        self.id = id
        self.is_resend = is_resend
        self.form_link = form_link

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        is_resend =\
            dictionary.get("is_resend")\
            if "is_resend" in dictionary.keys()\
                else None
        form_link =\
            dictionary.get("form_link")\
            if dictionary.get("form_link")\
                else None

        # Return an object of this model
        return cls(id,
                   is_resend,
                   form_link)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _is_resend=self.is_resend
        _form_link=self.form_link
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"is_resend={_is_resend!r}, "
            f"form_link={_form_link!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _is_resend=self.is_resend
        _form_link=self.form_link
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"is_resend={_is_resend!s}, "
            f"form_link={_form_link!s}, "
            f")"
        )
