"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class Errors(object):
    """Implementation of the 'Errors' model.

    Attributes:
        code (CodeEnum): The model property of type CodeEnum.
        message (str): The model property of type str.
        parameter (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": "code",
        "message": "message",
        "parameter": "parameter",
    }

    _optionals = [
        "code",
        "message",
        "parameter",
    ]

    def __init__(
        self,
        code=APIHelper.SKIP,
        message=APIHelper.SKIP,
        parameter=APIHelper.SKIP):
        """Initialize a Errors instance."""
        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code
        if message is not APIHelper.SKIP:
            self.message = message
        if parameter is not APIHelper.SKIP:
            self.parameter = parameter

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP
        parameter =\
            dictionary.get("parameter")\
            if dictionary.get("parameter")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(code,
                   message,
                   parameter)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _parameter=(
            self.parameter
            if hasattr(self, "parameter")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"code={_code!r}, "
            f"message={_message!r}, "
            f"parameter={_parameter!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _parameter=(
            self.parameter
            if hasattr(self, "parameter")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"code={_code!s}, "
            f"message={_message!s}, "
            f"parameter={_parameter!s}, "
            f")"
        )
