"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class Event(object):
    """Implementation of the 'event' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        resource (str): The type of resource for the event.
        event_name (str): The name of the event.
        event_time (datetime): The time of the event.
        data (Any): The body of the event.
        entity_id (str): The ID of the entity for the event.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "resource": "resource",
        "event_name": "event_name",
        "event_time": "event_time",
        "data": "data",
        "entity_id": "entity_id",
    }

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        resource=None,
        event_name=None,
        event_time=None,
        data=None,
        entity_id=None):
        """Initialize a Event instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.resource = resource
        self.event_name = event_name
        self.event_time =\
             APIHelper.apply_datetime_converter(
            event_time, APIHelper.RFC3339DateTime)\
             if event_time else None
        self.data = data
        self.entity_id = entity_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        resource =\
            dictionary.get("resource")\
            if dictionary.get("resource")\
                else None
        event_name =\
            dictionary.get("event_name")\
            if dictionary.get("event_name")\
                else None
        event_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("event_time")).datetime\
            if dictionary.get("event_time") else None
        data =\
            dictionary.get("data")\
            if dictionary.get("data")\
                else None
        entity_id =\
            dictionary.get("entity_id")\
            if dictionary.get("entity_id")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   resource,
                   event_name,
                   event_time,
                   data,
                   entity_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _resource=self.resource
        _event_name=self.event_name
        _event_time=self.event_time
        _data=self.data
        _entity_id=self.entity_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"resource={_resource!r}, "
            f"event_name={_event_name!r}, "
            f"event_time={_event_time!r}, "
            f"data={_data!r}, "
            f"entity_id={_entity_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _resource=self.resource
        _event_name=self.event_name
        _event_time=self.event_time
        _data=self.data
        _entity_id=self.entity_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"resource={_resource!s}, "
            f"event_name={_event_name!s}, "
            f"event_time={_event_time!s}, "
            f"data={_data!s}, "
            f"entity_id={_entity_id!s}, "
            f")"
        )
