"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from moderntreasury.api_helper import APIHelper


class ExpectedPaymentUpdateRequest(object):
    """Implementation of the 'expected_payment_update_request' model.

    Attributes:
        amount_upper_bound (int): The highest amount this expected payment may be
            equal to. Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        amount_lower_bound (int): The lowest amount this expected payment may be
            equal to. Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        direction (Direction1Enum): One of credit or debit. When you are receiving
            money, use credit. When you are being charged, use debit.
        internal_account_id (uuid|str): The ID of the Internal Account for the
            expected payment.
        mtype (Type1Enum): One of: ach, au_becs, bacs, book, check, eft, interac,
            provxchange, rtp, sen, sepa, signet, wire.
        currency (CurrencyEnum): Three-letter ISO currency code.
        date_upper_bound (date): The latest date the payment may come in. Format:
            yyyy-mm-dd
        date_lower_bound (date): The earliest date the payment may come in. Format:
            yyyy-mm-dd
        description (str): An optional description for internal use.
        statement_descriptor (str): The statement description you expect to see on
            the transaction. For ACH payments, this will be the full line item passed
            from the bank. For wire payments, this will be the OBI field on the wire.
            For check payments, this will be the memo field.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        counterparty_id (uuid|str): The ID of the counterparty you expect for this
            payment.
        remittance_information (str): For `ach`, this field will be passed through on
            an addenda record. For `wire` payments the field will be passed through
            as the "Originator to Beneficiary Information", also known as OBI or
            Fedwire tag 6000.
        reconciliation_groups (Any): The reconciliation groups you have for this
            payment.
        reconciliation_filters (Any): The reconciliation filters you have for this
            payment.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount_upper_bound": "amount_upper_bound",
        "amount_lower_bound": "amount_lower_bound",
        "direction": "direction",
        "internal_account_id": "internal_account_id",
        "mtype": "type",
        "currency": "currency",
        "date_upper_bound": "date_upper_bound",
        "date_lower_bound": "date_lower_bound",
        "description": "description",
        "statement_descriptor": "statement_descriptor",
        "metadata": "metadata",
        "counterparty_id": "counterparty_id",
        "remittance_information": "remittance_information",
        "reconciliation_groups": "reconciliation_groups",
        "reconciliation_filters": "reconciliation_filters",
    }

    _optionals = [
        "amount_upper_bound",
        "amount_lower_bound",
        "direction",
        "internal_account_id",
        "mtype",
        "currency",
        "date_upper_bound",
        "date_lower_bound",
        "description",
        "statement_descriptor",
        "metadata",
        "counterparty_id",
        "remittance_information",
        "reconciliation_groups",
        "reconciliation_filters",
    ]

    _nullables = [
        "mtype",
        "date_upper_bound",
        "date_lower_bound",
        "description",
        "statement_descriptor",
        "counterparty_id",
        "remittance_information",
        "reconciliation_groups",
        "reconciliation_filters",
    ]

    def __init__(
        self,
        amount_upper_bound=APIHelper.SKIP,
        amount_lower_bound=APIHelper.SKIP,
        direction=APIHelper.SKIP,
        internal_account_id=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        date_upper_bound=APIHelper.SKIP,
        date_lower_bound=APIHelper.SKIP,
        description=APIHelper.SKIP,
        statement_descriptor=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        counterparty_id=APIHelper.SKIP,
        remittance_information=APIHelper.SKIP,
        reconciliation_groups=APIHelper.SKIP,
        reconciliation_filters=APIHelper.SKIP):
        """Initialize a ExpectedPaymentUpdateRequest instance."""
        # Initialize members of the class
        if amount_upper_bound is not APIHelper.SKIP:
            self.amount_upper_bound = amount_upper_bound
        if amount_lower_bound is not APIHelper.SKIP:
            self.amount_lower_bound = amount_lower_bound
        if direction is not APIHelper.SKIP:
            self.direction = direction
        if internal_account_id is not APIHelper.SKIP:
            self.internal_account_id = internal_account_id
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if date_upper_bound is not APIHelper.SKIP:
            self.date_upper_bound = date_upper_bound
        if date_lower_bound is not APIHelper.SKIP:
            self.date_lower_bound = date_lower_bound
        if description is not APIHelper.SKIP:
            self.description = description
        if statement_descriptor is not APIHelper.SKIP:
            self.statement_descriptor = statement_descriptor
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if counterparty_id is not APIHelper.SKIP:
            self.counterparty_id = counterparty_id
        if remittance_information is not APIHelper.SKIP:
            self.remittance_information = remittance_information
        if reconciliation_groups is not APIHelper.SKIP:
            self.reconciliation_groups = reconciliation_groups
        if reconciliation_filters is not APIHelper.SKIP:
            self.reconciliation_filters = reconciliation_filters

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount_upper_bound =\
            dictionary.get("amount_upper_bound")\
            if dictionary.get("amount_upper_bound")\
                else APIHelper.SKIP
        amount_lower_bound =\
            dictionary.get("amount_lower_bound")\
            if dictionary.get("amount_lower_bound")\
                else APIHelper.SKIP
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else APIHelper.SKIP
        internal_account_id =\
            dictionary.get("internal_account_id")\
            if dictionary.get("internal_account_id")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if "type" in dictionary.keys()\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        if "date_upper_bound" in dictionary.keys():
            date_upper_bound = dateutil.parser.parse(
                dictionary.get("date_upper_bound")).date()\
                if dictionary.get("date_upper_bound") else None

        else:
            date_upper_bound = APIHelper.SKIP
        if "date_lower_bound" in dictionary.keys():
            date_lower_bound = dateutil.parser.parse(
                dictionary.get("date_lower_bound")).date()\
                if dictionary.get("date_lower_bound") else None

        else:
            date_lower_bound = APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        statement_descriptor =\
            dictionary.get("statement_descriptor")\
            if "statement_descriptor" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if "counterparty_id" in dictionary.keys()\
                else APIHelper.SKIP
        remittance_information =\
            dictionary.get("remittance_information")\
            if "remittance_information" in dictionary.keys()\
                else APIHelper.SKIP
        reconciliation_groups =\
            dictionary.get("reconciliation_groups")\
            if "reconciliation_groups" in dictionary.keys()\
                else APIHelper.SKIP
        reconciliation_filters =\
            dictionary.get("reconciliation_filters")\
            if "reconciliation_filters" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(amount_upper_bound,
                   amount_lower_bound,
                   direction,
                   internal_account_id,
                   mtype,
                   currency,
                   date_upper_bound,
                   date_lower_bound,
                   description,
                   statement_descriptor,
                   metadata,
                   counterparty_id,
                   remittance_information,
                   reconciliation_groups,
                   reconciliation_filters)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount_upper_bound=(
            self.amount_upper_bound
            if hasattr(self, "amount_upper_bound")
            else None
        )
        _amount_lower_bound=(
            self.amount_lower_bound
            if hasattr(self, "amount_lower_bound")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _internal_account_id=(
            self.internal_account_id
            if hasattr(self, "internal_account_id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _date_upper_bound=(
            self.date_upper_bound
            if hasattr(self, "date_upper_bound")
            else None
        )
        _date_lower_bound=(
            self.date_lower_bound
            if hasattr(self, "date_lower_bound")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _statement_descriptor=(
            self.statement_descriptor
            if hasattr(self, "statement_descriptor")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _remittance_information=(
            self.remittance_information
            if hasattr(self, "remittance_information")
            else None
        )
        _reconciliation_groups=(
            self.reconciliation_groups
            if hasattr(self, "reconciliation_groups")
            else None
        )
        _reconciliation_filters=(
            self.reconciliation_filters
            if hasattr(self, "reconciliation_filters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount_upper_bound={_amount_upper_bound!r}, "
            f"amount_lower_bound={_amount_lower_bound!r}, "
            f"direction={_direction!r}, "
            f"internal_account_id={_internal_account_id!r}, "
            f"mtype={_mtype!r}, "
            f"currency={_currency!r}, "
            f"date_upper_bound={_date_upper_bound!r}, "
            f"date_lower_bound={_date_lower_bound!r}, "
            f"description={_description!r}, "
            f"statement_descriptor={_statement_descriptor!r}, "
            f"metadata={_metadata!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"remittance_information={_remittance_information!r}, "
            f"reconciliation_groups={_reconciliation_groups!r}, "
            f"reconciliation_filters={_reconciliation_filters!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount_upper_bound=(
            self.amount_upper_bound
            if hasattr(self, "amount_upper_bound")
            else None
        )
        _amount_lower_bound=(
            self.amount_lower_bound
            if hasattr(self, "amount_lower_bound")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _internal_account_id=(
            self.internal_account_id
            if hasattr(self, "internal_account_id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _date_upper_bound=(
            self.date_upper_bound
            if hasattr(self, "date_upper_bound")
            else None
        )
        _date_lower_bound=(
            self.date_lower_bound
            if hasattr(self, "date_lower_bound")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _statement_descriptor=(
            self.statement_descriptor
            if hasattr(self, "statement_descriptor")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _remittance_information=(
            self.remittance_information
            if hasattr(self, "remittance_information")
            else None
        )
        _reconciliation_groups=(
            self.reconciliation_groups
            if hasattr(self, "reconciliation_groups")
            else None
        )
        _reconciliation_filters=(
            self.reconciliation_filters
            if hasattr(self, "reconciliation_filters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount_upper_bound={_amount_upper_bound!s}, "
            f"amount_lower_bound={_amount_lower_bound!s}, "
            f"direction={_direction!s}, "
            f"internal_account_id={_internal_account_id!s}, "
            f"mtype={_mtype!s}, "
            f"currency={_currency!s}, "
            f"date_upper_bound={_date_upper_bound!s}, "
            f"date_lower_bound={_date_lower_bound!s}, "
            f"description={_description!s}, "
            f"statement_descriptor={_statement_descriptor!s}, "
            f"metadata={_metadata!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"remittance_information={_remittance_information!s}, "
            f"reconciliation_groups={_reconciliation_groups!s}, "
            f"reconciliation_filters={_reconciliation_filters!s}, "
            f")"
        )
