"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.address_request import (
    AddressRequest,
)


class ExternalAccountUpdateRequest(object):
    """Implementation of the 'external_account_update_request' model.

    Attributes:
        party_type (PartyType): Either `individual` or `business`.
        account_type (AccountType): Can be `checking`, `savings` or `other`.
        counterparty_id (uuid|str): The model property of type uuid|str.
        name (str): A nickname for the external account. This is only for internal
            usage and won't affect any payments
        party_name (str): If this value isn't provided, it will be inherited from the
            counterparty's name.
        party_address (AddressRequest): The model property of type AddressRequest.
        metadata (Dict[str, str]): Additional data in the form of key-value pairs.
            Pairs can be removed by passing an empty string or `null` as the value.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "party_type": "party_type",
        "account_type": "account_type",
        "counterparty_id": "counterparty_id",
        "name": "name",
        "party_name": "party_name",
        "party_address": "party_address",
        "metadata": "metadata",
    }

    _optionals = [
        "party_type",
        "account_type",
        "counterparty_id",
        "name",
        "party_name",
        "party_address",
        "metadata",
    ]

    _nullables = [
        "party_type",
        "counterparty_id",
        "name",
    ]

    def __init__(
        self,
        party_type=APIHelper.SKIP,
        account_type=APIHelper.SKIP,
        counterparty_id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        party_name=APIHelper.SKIP,
        party_address=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ExternalAccountUpdateRequest instance."""
        # Initialize members of the class
        if party_type is not APIHelper.SKIP:
            self.party_type = party_type
        if account_type is not APIHelper.SKIP:
            self.account_type = account_type
        if counterparty_id is not APIHelper.SKIP:
            self.counterparty_id = counterparty_id
        if name is not APIHelper.SKIP:
            self.name = name
        if party_name is not APIHelper.SKIP:
            self.party_name = party_name
        if party_address is not APIHelper.SKIP:
            self.party_address = party_address
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        party_type =\
            dictionary.get("party_type")\
            if "party_type" in dictionary.keys()\
                else APIHelper.SKIP
        account_type =\
            dictionary.get("account_type")\
            if dictionary.get("account_type")\
                else APIHelper.SKIP
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if "counterparty_id" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if "name" in dictionary.keys()\
                else APIHelper.SKIP
        party_name =\
            dictionary.get("party_name")\
            if dictionary.get("party_name")\
                else APIHelper.SKIP
        party_address =\
            AddressRequest.from_dictionary(
                dictionary.get("party_address"))\
                if "party_address" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(party_type,
                   account_type,
                   counterparty_id,
                   name,
                   party_name,
                   party_address,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _party_type=(
            self.party_type
            if hasattr(self, "party_type")
            else None
        )
        _account_type=(
            self.account_type
            if hasattr(self, "account_type")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _party_name=(
            self.party_name
            if hasattr(self, "party_name")
            else None
        )
        _party_address=(
            self.party_address
            if hasattr(self, "party_address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"party_type={_party_type!r}, "
            f"account_type={_account_type!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"name={_name!r}, "
            f"party_name={_party_name!r}, "
            f"party_address={_party_address!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _party_type=(
            self.party_type
            if hasattr(self, "party_type")
            else None
        )
        _account_type=(
            self.account_type
            if hasattr(self, "account_type")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _party_name=(
            self.party_name
            if hasattr(self, "party_name")
            else None
        )
        _party_address=(
            self.party_address
            if hasattr(self, "party_address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"party_type={_party_type!s}, "
            f"account_type={_account_type!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"name={_name!s}, "
            f"party_name={_party_name!s}, "
            f"party_address={_party_address!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
