"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.account_detail import (
    AccountDetail,
)
from moderntreasury.models.address import Address
from moderntreasury.models.contact_detail import (
    ContactDetail,
)
from moderntreasury.models.routing_detail import (
    RoutingDetail,
)


class ExternalAccount(object):
    """Implementation of the 'external_account' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        account_type (AccountTypeEnum): Can be `checking`, `savings` or `other`.
        party_type (PartyTypeEnum): Either `individual` or `business`.
        party_address (Address): The model property of type Address.
        name (str): A nickname for the external account. This is only for internal
            usage and won't affect any payments
        counterparty_id (uuid|str): The model property of type uuid|str.
        account_details (List[AccountDetail]): The model property of type
            List[AccountDetail].
        routing_details (List[RoutingDetail]): The model property of type
            List[RoutingDetail].
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        party_name (str): The legal name of the entity which owns the account.
        contact_details (List[ContactDetail]): The model property of type
            List[ContactDetail].
        ledger_account_id (uuid|str): If the external account links to a ledger
            account in Modern Treasury, the id of the ledger account will be
            populated here.
        verification_status (VerificationStatusEnum): The model property of type
            VerificationStatusEnum.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "account_type": "account_type",
        "party_type": "party_type",
        "party_address": "party_address",
        "name": "name",
        "counterparty_id": "counterparty_id",
        "account_details": "account_details",
        "routing_details": "routing_details",
        "metadata": "metadata",
        "party_name": "party_name",
        "contact_details": "contact_details",
        "ledger_account_id": "ledger_account_id",
        "verification_status": "verification_status",
    }

    _nullables = [
        "discarded_at",
        "party_type",
        "party_address",
        "name",
        "counterparty_id",
        "ledger_account_id",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        account_type=None,
        party_type=None,
        party_address=None,
        name=None,
        counterparty_id=None,
        account_details=None,
        routing_details=None,
        metadata=None,
        party_name=None,
        contact_details=None,
        ledger_account_id=None,
        verification_status=None):
        """Initialize a ExternalAccount instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.account_type = account_type
        self.party_type = party_type
        self.party_address = party_address
        self.name = name
        self.counterparty_id = counterparty_id
        self.account_details = account_details
        self.routing_details = routing_details
        self.metadata = metadata
        self.party_name = party_name
        self.contact_details = contact_details
        self.ledger_account_id = ledger_account_id
        self.verification_status = verification_status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        account_type =\
            dictionary.get("account_type")\
            if dictionary.get("account_type")\
                else None
        party_type =\
            dictionary.get("party_type")\
            if dictionary.get("party_type")\
                else None
        party_address =\
            Address.from_dictionary(
                dictionary.get("party_address"))\
                if dictionary.get("party_address") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if dictionary.get("counterparty_id")\
                else None
        account_details = None
        if dictionary.get("account_details") is not None:
            account_details = [
                AccountDetail.from_dictionary(x)
                    for x in dictionary.get("account_details")
            ]
        routing_details = None
        if dictionary.get("routing_details") is not None:
            routing_details = [
                RoutingDetail.from_dictionary(x)
                    for x in dictionary.get("routing_details")
            ]
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None
        party_name =\
            dictionary.get("party_name")\
            if dictionary.get("party_name")\
                else None
        contact_details = None
        if dictionary.get("contact_details") is not None:
            contact_details = [
                ContactDetail.from_dictionary(x)
                    for x in dictionary.get("contact_details")
            ]
        ledger_account_id =\
            dictionary.get("ledger_account_id")\
            if dictionary.get("ledger_account_id")\
                else None
        verification_status =\
            dictionary.get("verification_status")\
            if dictionary.get("verification_status")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   account_type,
                   party_type,
                   party_address,
                   name,
                   counterparty_id,
                   account_details,
                   routing_details,
                   metadata,
                   party_name,
                   contact_details,
                   ledger_account_id,
                   verification_status)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _account_type=self.account_type
        _party_type=self.party_type
        _party_address=self.party_address
        _name=self.name
        _counterparty_id=self.counterparty_id
        _account_details=self.account_details
        _routing_details=self.routing_details
        _metadata=self.metadata
        _party_name=self.party_name
        _contact_details=self.contact_details
        _ledger_account_id=self.ledger_account_id
        _verification_status=self.verification_status
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"account_type={_account_type!r}, "
            f"party_type={_party_type!r}, "
            f"party_address={_party_address!r}, "
            f"name={_name!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"account_details={_account_details!r}, "
            f"routing_details={_routing_details!r}, "
            f"metadata={_metadata!r}, "
            f"party_name={_party_name!r}, "
            f"contact_details={_contact_details!r}, "
            f"ledger_account_id={_ledger_account_id!r}, "
            f"verification_status={_verification_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _account_type=self.account_type
        _party_type=self.party_type
        _party_address=self.party_address
        _name=self.name
        _counterparty_id=self.counterparty_id
        _account_details=self.account_details
        _routing_details=self.routing_details
        _metadata=self.metadata
        _party_name=self.party_name
        _contact_details=self.contact_details
        _ledger_account_id=self.ledger_account_id
        _verification_status=self.verification_status
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"account_type={_account_type!s}, "
            f"party_type={_party_type!s}, "
            f"party_address={_party_address!s}, "
            f"name={_name!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"account_details={_account_details!s}, "
            f"routing_details={_routing_details!s}, "
            f"metadata={_metadata!s}, "
            f"party_name={_party_name!s}, "
            f"contact_details={_contact_details!s}, "
            f"ledger_account_id={_ledger_account_id!s}, "
            f"verification_status={_verification_status!s}, "
            f")"
        )
