"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class ExternalAccountVerifyRequest(object):
    """Implementation of the 'external_account_verify_request' model.

    Attributes:
        originating_account_id (uuid|str): The ID of the internal account where the
            micro-deposits originate from. Both credit and debit capabilities must be
            enabled.
        payment_type (PaymentType4): Both ach and eft are supported payment types.
        currency (Currency): Three-letter ISO currency code.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "originating_account_id": "originating_account_id",
        "payment_type": "payment_type",
        "currency": "currency",
    }

    _optionals = [
        "currency",
    ]

    def __init__(
        self,
        originating_account_id=None,
        payment_type=None,
        currency=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ExternalAccountVerifyRequest instance."""
        # Initialize members of the class
        self.originating_account_id = originating_account_id
        self.payment_type = payment_type
        if currency is not APIHelper.SKIP:
            self.currency = currency

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        originating_account_id =\
            dictionary.get("originating_account_id")\
            if dictionary.get("originating_account_id")\
                else None
        payment_type =\
            dictionary.get("payment_type")\
            if dictionary.get("payment_type")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(originating_account_id,
                   payment_type,
                   currency,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _originating_account_id=self.originating_account_id
        _payment_type=self.payment_type
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"originating_account_id={_originating_account_id!r}, "
            f"payment_type={_payment_type!r}, "
            f"currency={_currency!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _originating_account_id=self.originating_account_id
        _payment_type=self.payment_type
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"originating_account_id={_originating_account_id!s}, "
            f"payment_type={_payment_type!s}, "
            f"currency={_currency!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
