"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ForeignExchangeIndicatorEnum(object):
    """Implementation of the 'ForeignExchangeIndicator' enum.

    Indicates the type of FX transfer to initiate, can be either `variable_to_fixed`,
    `fixed_to_variable`, or `null` if the payment order currency matches the
    originating account currency.

    Attributes:
        FIXED_TO_VARIABLE: The enum member of type str.
        VARIABLE_TO_FIXED: The enum member of type str.

    """

    _all_values = ["fixed_to_variable", "variable_to_fixed"]
    FIXED_TO_VARIABLE = "fixed_to_variable"

    VARIABLE_TO_FIXED = "variable_to_fixed"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
