"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from moderntreasury.api_helper import APIHelper


class IncomingPaymentDetailCreateRequest(object):
    """Implementation of the 'incoming_payment_detail_create_request' model.

    Attributes:
        mtype (Type10): One of `ach`, `wire`, `check`.
        direction (Direction14): One of `credit`, `debit`.
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        currency (Currency): Three-letter ISO currency code.
        internal_account_id (uuid|str): The ID of one of your internal accounts.
        virtual_account_id (uuid|str): An optional parameter to associate the
            incoming payment detail to a virtual account.
        as_of_date (date): Defaults to today.
        description (str): Defaults to a random description.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "direction": "direction",
        "amount": "amount",
        "currency": "currency",
        "internal_account_id": "internal_account_id",
        "virtual_account_id": "virtual_account_id",
        "as_of_date": "as_of_date",
        "description": "description",
    }

    _optionals = [
        "mtype",
        "direction",
        "amount",
        "currency",
        "internal_account_id",
        "virtual_account_id",
        "as_of_date",
        "description",
    ]

    _nullables = [
        "virtual_account_id",
        "as_of_date",
        "description",
    ]

    def __init__(
        self,
        mtype=APIHelper.SKIP,
        direction=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        internal_account_id=APIHelper.SKIP,
        virtual_account_id=APIHelper.SKIP,
        as_of_date=APIHelper.SKIP,
        description=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IncomingPaymentDetailCreateRequest instance."""
        # Initialize members of the class
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if direction is not APIHelper.SKIP:
            self.direction = direction
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if internal_account_id is not APIHelper.SKIP:
            self.internal_account_id = internal_account_id
        if virtual_account_id is not APIHelper.SKIP:
            self.virtual_account_id = virtual_account_id
        if as_of_date is not APIHelper.SKIP:
            self.as_of_date = as_of_date
        if description is not APIHelper.SKIP:
            self.description = description

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        internal_account_id =\
            dictionary.get("internal_account_id")\
            if dictionary.get("internal_account_id")\
                else APIHelper.SKIP
        virtual_account_id =\
            dictionary.get("virtual_account_id")\
            if "virtual_account_id" in dictionary.keys()\
                else APIHelper.SKIP
        if "as_of_date" in dictionary.keys():
            as_of_date = dateutil.parser.parse(
                dictionary.get("as_of_date")).date()\
                if dictionary.get("as_of_date") else None

        else:
            as_of_date = APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   direction,
                   amount,
                   currency,
                   internal_account_id,
                   virtual_account_id,
                   as_of_date,
                   description,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _internal_account_id=(
            self.internal_account_id
            if hasattr(self, "internal_account_id")
            else None
        )
        _virtual_account_id=(
            self.virtual_account_id
            if hasattr(self, "virtual_account_id")
            else None
        )
        _as_of_date=(
            self.as_of_date
            if hasattr(self, "as_of_date")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"direction={_direction!r}, "
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"internal_account_id={_internal_account_id!r}, "
            f"virtual_account_id={_virtual_account_id!r}, "
            f"as_of_date={_as_of_date!r}, "
            f"description={_description!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _internal_account_id=(
            self.internal_account_id
            if hasattr(self, "internal_account_id")
            else None
        )
        _virtual_account_id=(
            self.virtual_account_id
            if hasattr(self, "virtual_account_id")
            else None
        )
        _as_of_date=(
            self.as_of_date
            if hasattr(self, "as_of_date")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"direction={_direction!s}, "
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"internal_account_id={_internal_account_id!s}, "
            f"virtual_account_id={_virtual_account_id!s}, "
            f"as_of_date={_as_of_date!s}, "
            f"description={_description!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
