"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_entry_create_request import (
    LedgerEntryCreateRequest,
)


class LedgerTransactionCreateRequest(object):
    """Implementation of the 'ledger_transaction_create_request' model.

    Attributes:
        description (str): An optional description for internal use.
        status (Status11): To post a ledger transaction at creation, use `posted`.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        effective_at (date): The timestamp (ISO8601 format) at which the ledger
            transaction happened for reporting purposes.
        effective_date (date): The date (YYYY-MM-DD) on which the ledger transaction
            happened for reporting purposes.
        ledger_entries (List[LedgerEntryCreateRequest]): An array of ledger entry
            objects.
        external_id (str): A unique string to represent the ledger transaction. Only
            one pending or posted ledger transaction may have this ID in the ledger.
        ledgerable_type (LedgerableType2): If the ledger transaction can be
            reconciled to another object in Modern Treasury, the type will be
            populated here, otherwise null. This can be one of payment_order,
            incoming_payment_detail, expected_payment, return, or reversal.
        ledgerable_id (uuid|str): If the ledger transaction can be reconciled to
            another object in Modern Treasury, the id will be populated here,
            otherwise null.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ledger_entries": "ledger_entries",
        "description": "description",
        "status": "status",
        "metadata": "metadata",
        "effective_at": "effective_at",
        "effective_date": "effective_date",
        "external_id": "external_id",
        "ledgerable_type": "ledgerable_type",
        "ledgerable_id": "ledgerable_id",
    }

    _optionals = [
        "description",
        "status",
        "metadata",
        "effective_at",
        "effective_date",
        "external_id",
        "ledgerable_type",
        "ledgerable_id",
    ]

    _nullables = [
        "description",
    ]

    def __init__(
        self,
        ledger_entries=None,
        description=APIHelper.SKIP,
        status=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        effective_at=APIHelper.SKIP,
        effective_date=APIHelper.SKIP,
        external_id=APIHelper.SKIP,
        ledgerable_type=APIHelper.SKIP,
        ledgerable_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a LedgerTransactionCreateRequest instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if status is not APIHelper.SKIP:
            self.status = status
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if effective_at is not APIHelper.SKIP:
            self.effective_at = effective_at
        if effective_date is not APIHelper.SKIP:
            self.effective_date = effective_date
        self.ledger_entries = ledger_entries
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        if ledgerable_type is not APIHelper.SKIP:
            self.ledgerable_type = ledgerable_type
        if ledgerable_id is not APIHelper.SKIP:
            self.ledgerable_id = ledgerable_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ledger_entries = None
        if dictionary.get("ledger_entries") is not None:
            ledger_entries = [
                LedgerEntryCreateRequest.from_dictionary(x)
                    for x in dictionary.get("ledger_entries")
            ]
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        effective_at = dateutil.parser.parse(
            dictionary.get("effective_at")).date()\
            if dictionary.get("effective_at") else APIHelper.SKIP
        effective_date = dateutil.parser.parse(
            dictionary.get("effective_date")).date()\
            if dictionary.get("effective_date") else APIHelper.SKIP
        external_id =\
            dictionary.get("external_id")\
            if dictionary.get("external_id")\
                else APIHelper.SKIP
        ledgerable_type =\
            dictionary.get("ledgerable_type")\
            if dictionary.get("ledgerable_type")\
                else APIHelper.SKIP
        ledgerable_id =\
            dictionary.get("ledgerable_id")\
            if dictionary.get("ledgerable_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ledger_entries,
                   description,
                   status,
                   metadata,
                   effective_at,
                   effective_date,
                   external_id,
                   ledgerable_type,
                   ledgerable_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _effective_at=(
            self.effective_at
            if hasattr(self, "effective_at")
            else None
        )
        _effective_date=(
            self.effective_date
            if hasattr(self, "effective_date")
            else None
        )
        _ledger_entries=self.ledger_entries
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _ledgerable_type=(
            self.ledgerable_type
            if hasattr(self, "ledgerable_type")
            else None
        )
        _ledgerable_id=(
            self.ledgerable_id
            if hasattr(self, "ledgerable_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"status={_status!r}, "
            f"metadata={_metadata!r}, "
            f"effective_at={_effective_at!r}, "
            f"effective_date={_effective_date!r}, "
            f"ledger_entries={_ledger_entries!r}, "
            f"external_id={_external_id!r}, "
            f"ledgerable_type={_ledgerable_type!r}, "
            f"ledgerable_id={_ledgerable_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _effective_at=(
            self.effective_at
            if hasattr(self, "effective_at")
            else None
        )
        _effective_date=(
            self.effective_date
            if hasattr(self, "effective_date")
            else None
        )
        _ledger_entries=self.ledger_entries
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _ledgerable_type=(
            self.ledgerable_type
            if hasattr(self, "ledgerable_type")
            else None
        )
        _ledgerable_id=(
            self.ledgerable_id
            if hasattr(self, "ledgerable_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"status={_status!s}, "
            f"metadata={_metadata!s}, "
            f"effective_at={_effective_at!s}, "
            f"effective_date={_effective_date!s}, "
            f"ledger_entries={_ledger_entries!s}, "
            f"external_id={_external_id!s}, "
            f"ledgerable_type={_ledgerable_type!s}, "
            f"ledgerable_id={_ledgerable_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
