"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class LedgerableEvent(object):
    """Implementation of the 'ledgerable_event' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        name (str): Name of the ledgerable event.
        description (str): Description of the ledgerable event.
        direction (str): One of `credit`, `debit`.
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        currency (str): An ISO 4217 conformed currency or a custom currency.
        currency_exponent (int): Must be included if currency is a custom currency.
            The currency_exponent cannot exceed 30.
        custom_data (Any): Additionally data to be used by the Ledger Event Handler.
        ledger_event_handler_id (uuid|str): Id of the ledger event handler that is
            used to create a ledger transaction.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "name": "name",
        "description": "description",
        "direction": "direction",
        "amount": "amount",
        "currency": "currency",
        "currency_exponent": "currency_exponent",
        "custom_data": "custom_data",
        "ledger_event_handler_id": "ledger_event_handler_id",
        "metadata": "metadata",
    }

    _nullables = [
        "description",
        "direction",
        "currency_exponent",
        "custom_data",
        "metadata",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        name=None,
        description=None,
        direction=None,
        amount=None,
        currency=None,
        currency_exponent=None,
        custom_data=None,
        ledger_event_handler_id=None,
        metadata=None):
        """Initialize a LedgerableEvent instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.name = name
        self.description = description
        self.direction = direction
        self.amount = amount
        self.currency = currency
        self.currency_exponent = currency_exponent
        self.custom_data = custom_data
        self.ledger_event_handler_id = ledger_event_handler_id
        self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else None
        currency_exponent =\
            dictionary.get("currency_exponent")\
            if dictionary.get("currency_exponent")\
                else None
        custom_data =\
            dictionary.get("custom_data")\
            if dictionary.get("custom_data")\
                else None
        ledger_event_handler_id =\
            dictionary.get("ledger_event_handler_id")\
            if dictionary.get("ledger_event_handler_id")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   name,
                   description,
                   direction,
                   amount,
                   currency,
                   currency_exponent,
                   custom_data,
                   ledger_event_handler_id,
                   metadata)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _name=self.name
        _description=self.description
        _direction=self.direction
        _amount=self.amount
        _currency=self.currency
        _currency_exponent=self.currency_exponent
        _custom_data=self.custom_data
        _ledger_event_handler_id=self.ledger_event_handler_id
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"direction={_direction!r}, "
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"currency_exponent={_currency_exponent!r}, "
            f"custom_data={_custom_data!r}, "
            f"ledger_event_handler_id={_ledger_event_handler_id!r}, "
            f"metadata={_metadata!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _name=self.name
        _description=self.description
        _direction=self.direction
        _amount=self.amount
        _currency=self.currency
        _currency_exponent=self.currency_exponent
        _custom_data=self.custom_data
        _ledger_event_handler_id=self.ledger_event_handler_id
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"direction={_direction!s}, "
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"currency_exponent={_currency_exponent!s}, "
            f"custom_data={_custom_data!s}, "
            f"ledger_event_handler_id={_ledger_event_handler_id!s}, "
            f"metadata={_metadata!s}, "
            f")"
        )
