"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_event_handler_conditions import (
    LedgerEventHandlerConditions,
)
from moderntreasury.models.ledger_event_handler_ledger_transaction_template import (
    LedgerEventHandlerLedgerTransactionTemplate,
)


class LedgerEventHandlerCreateRequest(object):
    """Implementation of the 'ledger_event_handler_create_request' model.

    Attributes:
        name (str): Name of the ledger event handler.
        description (str): An optional description.
        ledger_id (uuid|str): The id of the ledger that this account belongs to.
        ledger_transaction_template (LedgerEventHandlerLedgerTransactionTemplate):
            The model property of type LedgerEventHandlerLedgerTransactionTemplate.
        conditions (LedgerEventHandlerConditions): The model property of type
            LedgerEventHandlerConditions.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "ledger_transaction_template": "ledger_transaction_template",
        "description": "description",
        "ledger_id": "ledger_id",
        "conditions": "conditions",
        "metadata": "metadata",
    }

    _optionals = [
        "description",
        "ledger_id",
        "conditions",
        "metadata",
    ]

    _nullables = [
        "description",
        "metadata",
    ]

    def __init__(
        self,
        name=None,
        ledger_transaction_template=None,
        description=APIHelper.SKIP,
        ledger_id=APIHelper.SKIP,
        conditions=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a LedgerEventHandlerCreateRequest instance."""
        # Initialize members of the class
        self.name = name
        if description is not APIHelper.SKIP:
            self.description = description
        if ledger_id is not APIHelper.SKIP:
            self.ledger_id = ledger_id
        self.ledger_transaction_template = ledger_transaction_template
        if conditions is not APIHelper.SKIP:
            self.conditions = conditions
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        ledger_transaction_template =\
            LedgerEventHandlerLedgerTransactionTemplate.from_dictionary(
                dictionary.get("ledger_transaction_template"))\
                if dictionary.get("ledger_transaction_template") else None
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        ledger_id =\
            dictionary.get("ledger_id")\
            if dictionary.get("ledger_id")\
                else APIHelper.SKIP
        conditions =\
            LedgerEventHandlerConditions.from_dictionary(
                dictionary.get("conditions"))\
                if "conditions" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if "metadata" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   ledger_transaction_template,
                   description,
                   ledger_id,
                   conditions,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _ledger_id=(
            self.ledger_id
            if hasattr(self, "ledger_id")
            else None
        )
        _ledger_transaction_template=self.ledger_transaction_template
        _conditions=(
            self.conditions
            if hasattr(self, "conditions")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"ledger_id={_ledger_id!r}, "
            f"ledger_transaction_template={_ledger_transaction_template!r}, "
            f"conditions={_conditions!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _ledger_id=(
            self.ledger_id
            if hasattr(self, "ledger_id")
            else None
        )
        _ledger_transaction_template=self.ledger_transaction_template
        _conditions=(
            self.conditions
            if hasattr(self, "conditions")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"ledger_id={_ledger_id!s}, "
            f"ledger_transaction_template={_ledger_transaction_template!s}, "
            f"conditions={_conditions!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
