"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class LedgerAccountPayoutCreateRequest(object):
    """Implementation of the 'ledger_account_payout_create_request' model.

    Attributes:
        description (str): The description of the ledger account payout.
        status (Status7Enum): The status of the ledger account payout. It is set to
            `pending` by default. To post a ledger account payout at creation, use
            `posted`.
        payout_ledger_account_id (uuid|str): The id of the payout ledger account
            whose ledger entries are queried against, and its balance is reduced as a
            result.
        funding_ledger_account_id (uuid|str): The id of the funding ledger account
            that sends to or receives funds from the payout ledger account.
        effective_at_upper_bound (datetime): The exclusive upper bound of the
            effective_at timestamp of the ledger entries to be included in the ledger
            account payout. The default value is the created_at timestamp of the
            ledger account payout.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        skip_payout_ledger_transaction (bool): It is set to `false` by default. It
            should be set to `true` when migrating existing payouts.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payout_ledger_account_id": "payout_ledger_account_id",
        "funding_ledger_account_id": "funding_ledger_account_id",
        "description": "description",
        "status": "status",
        "effective_at_upper_bound": "effective_at_upper_bound",
        "metadata": "metadata",
        "skip_payout_ledger_transaction": "skip_payout_ledger_transaction",
    }

    _optionals = [
        "description",
        "status",
        "effective_at_upper_bound",
        "metadata",
        "skip_payout_ledger_transaction",
    ]

    _nullables = [
        "description",
        "status",
        "effective_at_upper_bound",
        "skip_payout_ledger_transaction",
    ]

    def __init__(
        self,
        payout_ledger_account_id=None,
        funding_ledger_account_id=None,
        description=APIHelper.SKIP,
        status=APIHelper.SKIP,
        effective_at_upper_bound=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        skip_payout_ledger_transaction=APIHelper.SKIP):
        """Initialize a LedgerAccountPayoutCreateRequest instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if status is not APIHelper.SKIP:
            self.status = status
        self.payout_ledger_account_id = payout_ledger_account_id
        self.funding_ledger_account_id = funding_ledger_account_id
        if effective_at_upper_bound is not APIHelper.SKIP:
            self.effective_at_upper_bound =\
                 APIHelper.apply_datetime_converter(
                effective_at_upper_bound, APIHelper.RFC3339DateTime)\
                 if effective_at_upper_bound else None
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if skip_payout_ledger_transaction is not APIHelper.SKIP:
            self.skip_payout_ledger_transaction = skip_payout_ledger_transaction

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payout_ledger_account_id =\
            dictionary.get("payout_ledger_account_id")\
            if dictionary.get("payout_ledger_account_id")\
                else None
        funding_ledger_account_id =\
            dictionary.get("funding_ledger_account_id")\
            if dictionary.get("funding_ledger_account_id")\
                else None
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if "status" in dictionary.keys()\
                else APIHelper.SKIP
        if "effective_at_upper_bound" in dictionary.keys():
            effective_at_upper_bound = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("effective_at_upper_bound")).datetime\
                if dictionary.get("effective_at_upper_bound") else None

        else:
            effective_at_upper_bound = APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        skip_payout_ledger_transaction =\
            dictionary.get("skip_payout_ledger_transaction")\
            if "skip_payout_ledger_transaction" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(payout_ledger_account_id,
                   funding_ledger_account_id,
                   description,
                   status,
                   effective_at_upper_bound,
                   metadata,
                   skip_payout_ledger_transaction)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _payout_ledger_account_id=self.payout_ledger_account_id
        _funding_ledger_account_id=self.funding_ledger_account_id
        _effective_at_upper_bound=(
            self.effective_at_upper_bound
            if hasattr(self, "effective_at_upper_bound")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _skip_payout_ledger_transaction=(
            self.skip_payout_ledger_transaction
            if hasattr(self, "skip_payout_ledger_transaction")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"status={_status!r}, "
            f"payout_ledger_account_id={_payout_ledger_account_id!r}, "
            f"funding_ledger_account_id={_funding_ledger_account_id!r}, "
            f"effective_at_upper_bound={_effective_at_upper_bound!r}, "
            f"metadata={_metadata!r}, "
            f"skip_payout_ledger_transaction={_skip_payout_ledger_transaction!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _payout_ledger_account_id=self.payout_ledger_account_id
        _funding_ledger_account_id=self.funding_ledger_account_id
        _effective_at_upper_bound=(
            self.effective_at_upper_bound
            if hasattr(self, "effective_at_upper_bound")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _skip_payout_ledger_transaction=(
            self.skip_payout_ledger_transaction
            if hasattr(self, "skip_payout_ledger_transaction")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"status={_status!s}, "
            f"payout_ledger_account_id={_payout_ledger_account_id!s}, "
            f"funding_ledger_account_id={_funding_ledger_account_id!s}, "
            f"effective_at_upper_bound={_effective_at_upper_bound!s}, "
            f"metadata={_metadata!s}, "
            f"skip_payout_ledger_transaction={_skip_payout_ledger_transaction!s}, "
            f")"
        )
