"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_balances import (
    LedgerBalances,
)


class LedgerAccountCategory(object):
    """Implementation of the 'ledger_account_category' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        name (str): The name of the ledger account category.
        description (str): The description of the ledger account category.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        ledger_id (uuid|str): The id of the ledger that this account category belongs
            to.
        normal_balance (NormalBalance2): The normal balance of the ledger account
            category.
        balances (LedgerBalances): The model property of type LedgerBalances.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "name": "name",
        "description": "description",
        "metadata": "metadata",
        "ledger_id": "ledger_id",
        "normal_balance": "normal_balance",
        "balances": "balances",
    }

    _nullables = [
        "discarded_at",
        "description",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        name=None,
        description=None,
        metadata=None,
        ledger_id=None,
        normal_balance=None,
        balances=None):
        """Initialize a LedgerAccountCategory instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.name = name
        self.description = description
        self.metadata = metadata
        self.ledger_id = ledger_id
        self.normal_balance = normal_balance
        self.balances = balances

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None
        ledger_id =\
            dictionary.get("ledger_id")\
            if dictionary.get("ledger_id")\
                else None
        normal_balance =\
            dictionary.get("normal_balance")\
            if dictionary.get("normal_balance")\
                else None
        balances =\
            LedgerBalances.from_dictionary(
                dictionary.get("balances"))\
                if dictionary.get("balances") else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   name,
                   description,
                   metadata,
                   ledger_id,
                   normal_balance,
                   balances)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _metadata=self.metadata
        _ledger_id=self.ledger_id
        _normal_balance=self.normal_balance
        _balances=self.balances
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"metadata={_metadata!r}, "
            f"ledger_id={_ledger_id!r}, "
            f"normal_balance={_normal_balance!r}, "
            f"balances={_balances!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _metadata=self.metadata
        _ledger_id=self.ledger_id
        _normal_balance=self.normal_balance
        _balances=self.balances
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"metadata={_metadata!s}, "
            f"ledger_id={_ledger_id!s}, "
            f"normal_balance={_normal_balance!s}, "
            f"balances={_balances!s}, "
            f")"
        )
