"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_balances import (
    LedgerBalances,
)


class LedgerAccountStatement(object):
    """Implementation of the 'ledger_account_statement' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        ledger_id (uuid|str): The id of the ledger that this ledger account statement
            belongs to.
        description (str): The description of the ledger account statement.
        ledger_account_id (uuid|str): The id of the ledger account whose ledger
            entries are queried against, and its balances are computed as a result.
        ledger_account_lock_version (int): Lock version of the ledger account at the
            time of statement generation.
        ledger_account_normal_balance (LedgerAccountNormalBalanceEnum): The normal
            balance of the ledger account.
        effective_at_lower_bound (datetime): The inclusive lower bound of the
            effective_at timestamp of the ledger entries to be included in the ledger
            account statement.
        effective_at_upper_bound (datetime): The exclusive upper bound of the
            effective_at timestamp of the ledger entries to be included in the ledger
            account statement.
        starting_balance (LedgerBalances): The model property of type LedgerBalances.
        ending_balance (LedgerBalances): The model property of type LedgerBalances.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "ledger_id": "ledger_id",
        "description": "description",
        "ledger_account_id": "ledger_account_id",
        "ledger_account_lock_version": "ledger_account_lock_version",
        "ledger_account_normal_balance": "ledger_account_normal_balance",
        "effective_at_lower_bound": "effective_at_lower_bound",
        "effective_at_upper_bound": "effective_at_upper_bound",
        "starting_balance": "starting_balance",
        "ending_balance": "ending_balance",
        "metadata": "metadata",
    }

    _nullables = [
        "description",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        ledger_id=None,
        description=None,
        ledger_account_id=None,
        ledger_account_lock_version=None,
        ledger_account_normal_balance=None,
        effective_at_lower_bound=None,
        effective_at_upper_bound=None,
        starting_balance=None,
        ending_balance=None,
        metadata=None):
        """Initialize a LedgerAccountStatement instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.ledger_id = ledger_id
        self.description = description
        self.ledger_account_id = ledger_account_id
        self.ledger_account_lock_version = ledger_account_lock_version
        self.ledger_account_normal_balance = ledger_account_normal_balance
        self.effective_at_lower_bound =\
             APIHelper.apply_datetime_converter(
            effective_at_lower_bound, APIHelper.RFC3339DateTime)\
             if effective_at_lower_bound else None
        self.effective_at_upper_bound =\
             APIHelper.apply_datetime_converter(
            effective_at_upper_bound, APIHelper.RFC3339DateTime)\
             if effective_at_upper_bound else None
        self.starting_balance = starting_balance
        self.ending_balance = ending_balance
        self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        ledger_id =\
            dictionary.get("ledger_id")\
            if dictionary.get("ledger_id")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        ledger_account_id =\
            dictionary.get("ledger_account_id")\
            if dictionary.get("ledger_account_id")\
                else None
        ledger_account_lock_version =\
            dictionary.get("ledger_account_lock_version")\
            if dictionary.get("ledger_account_lock_version")\
                else None
        ledger_account_normal_balance =\
            dictionary.get("ledger_account_normal_balance")\
            if dictionary.get("ledger_account_normal_balance")\
                else None
        effective_at_lower_bound = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("effective_at_lower_bound")).datetime\
            if dictionary.get("effective_at_lower_bound") else None
        effective_at_upper_bound = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("effective_at_upper_bound")).datetime\
            if dictionary.get("effective_at_upper_bound") else None
        starting_balance =\
            LedgerBalances.from_dictionary(
                dictionary.get("starting_balance"))\
                if dictionary.get("starting_balance") else None
        ending_balance =\
            LedgerBalances.from_dictionary(
                dictionary.get("ending_balance"))\
                if dictionary.get("ending_balance") else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   ledger_id,
                   description,
                   ledger_account_id,
                   ledger_account_lock_version,
                   ledger_account_normal_balance,
                   effective_at_lower_bound,
                   effective_at_upper_bound,
                   starting_balance,
                   ending_balance,
                   metadata)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _ledger_id=self.ledger_id
        _description=self.description
        _ledger_account_id=self.ledger_account_id
        _ledger_account_lock_version=self.ledger_account_lock_version
        _ledger_account_normal_balance=self.ledger_account_normal_balance
        _effective_at_lower_bound=self.effective_at_lower_bound
        _effective_at_upper_bound=self.effective_at_upper_bound
        _starting_balance=self.starting_balance
        _ending_balance=self.ending_balance
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"ledger_id={_ledger_id!r}, "
            f"description={_description!r}, "
            f"ledger_account_id={_ledger_account_id!r}, "
            f"ledger_account_lock_version={_ledger_account_lock_version!r}, "
            f"ledger_account_normal_balance={_ledger_account_normal_balance!r}, "
            f"effective_at_lower_bound={_effective_at_lower_bound!r}, "
            f"effective_at_upper_bound={_effective_at_upper_bound!r}, "
            f"starting_balance={_starting_balance!r}, "
            f"ending_balance={_ending_balance!r}, "
            f"metadata={_metadata!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _ledger_id=self.ledger_id
        _description=self.description
        _ledger_account_id=self.ledger_account_id
        _ledger_account_lock_version=self.ledger_account_lock_version
        _ledger_account_normal_balance=self.ledger_account_normal_balance
        _effective_at_lower_bound=self.effective_at_lower_bound
        _effective_at_upper_bound=self.effective_at_upper_bound
        _starting_balance=self.starting_balance
        _ending_balance=self.ending_balance
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"ledger_id={_ledger_id!s}, "
            f"description={_description!s}, "
            f"ledger_account_id={_ledger_account_id!s}, "
            f"ledger_account_lock_version={_ledger_account_lock_version!s}, "
            f"ledger_account_normal_balance={_ledger_account_normal_balance!s}, "
            f"effective_at_lower_bound={_effective_at_lower_bound!s}, "
            f"effective_at_upper_bound={_effective_at_upper_bound!s}, "
            f"starting_balance={_starting_balance!s}, "
            f"ending_balance={_ending_balance!s}, "
            f"metadata={_metadata!s}, "
            f")"
        )
