"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.models.ledger_balance import (
    LedgerBalance,
)


class LedgerBalances(object):
    """Implementation of the 'ledger_balances' model.

    Attributes:
        pending_balance (LedgerBalance): The model property of type LedgerBalance.
        posted_balance (LedgerBalance): The model property of type LedgerBalance.
        available_balance (LedgerBalance): The model property of type LedgerBalance.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pending_balance": "pending_balance",
        "posted_balance": "posted_balance",
        "available_balance": "available_balance",
    }

    def __init__(
        self,
        pending_balance=None,
        posted_balance=None,
        available_balance=None):
        """Initialize a LedgerBalances instance."""
        # Initialize members of the class
        self.pending_balance = pending_balance
        self.posted_balance = posted_balance
        self.available_balance = available_balance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        pending_balance =\
            LedgerBalance.from_dictionary(
                dictionary.get("pending_balance"))\
                if dictionary.get("pending_balance") else None
        posted_balance =\
            LedgerBalance.from_dictionary(
                dictionary.get("posted_balance"))\
                if dictionary.get("posted_balance") else None
        available_balance =\
            LedgerBalance.from_dictionary(
                dictionary.get("available_balance"))\
                if dictionary.get("available_balance") else None

        # Return an object of this model
        return cls(pending_balance,
                   posted_balance,
                   available_balance)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _pending_balance=self.pending_balance
        _posted_balance=self.posted_balance
        _available_balance=self.available_balance
        return (
            f"{self.__class__.__name__}("
            f"pending_balance={_pending_balance!r}, "
            f"posted_balance={_posted_balance!r}, "
            f"available_balance={_available_balance!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _pending_balance=self.pending_balance
        _posted_balance=self.posted_balance
        _available_balance=self.available_balance
        return (
            f"{self.__class__.__name__}("
            f"pending_balance={_pending_balance!s}, "
            f"posted_balance={_posted_balance!s}, "
            f"available_balance={_available_balance!s}, "
            f")"
        )
