"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class LedgerableType2Enum(object):
    """Implementation of the 'LedgerableType2' enum.

    If the ledger transaction can be reconciled to another object in Modern Treasury,
    the type will be populated here, otherwise null. This can be one of
    payment_order, incoming_payment_detail, expected_payment, return, or reversal.

    Attributes:
        COUNTERPARTY: The enum member of type str.
        EXPECTED_PAYMENT: The enum member of type str.
        INCOMING_PAYMENT_DETAIL: The enum member of type str.
        INTERNAL_ACCOUNT: The enum member of type str.
        LINE_ITEM: The enum member of type str.
        PAPER_ITEM: The enum member of type str.
        PAYMENT_ORDER: The enum member of type str.
        PAYMENT_ORDER_ATTEMPT: The enum member of type str.
        RETURN: The enum member of type str.
        REVERSAL: The enum member of type str.

    """

    COUNTERPARTY = "counterparty"

    EXPECTED_PAYMENT = "expected_payment"

    INCOMING_PAYMENT_DETAIL = "incoming_payment_detail"

    INTERNAL_ACCOUNT = "internal_account"

    LINE_ITEM = "line_item"

    PAPER_ITEM = "paper_item"

    PAYMENT_ORDER = "payment_order"

    PAYMENT_ORDER_ATTEMPT = "payment_order_attempt"

    ENUM_RETURN = "return"

    REVERSAL = "reversal"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
