"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_balances_with_effective_at import (
    LedgerBalancesWithEffectiveAt,
)


class LedgerAccount(object):
    """Implementation of the 'ledger_account' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        name (str): The name of the ledger account.
        description (str): The description of the ledger account.
        normal_balance (NormalBalanceEnum): The normal balance of the ledger account.
        balances (LedgerBalancesWithEffectiveAt): The model property of type
            LedgerBalancesWithEffectiveAt.
        lock_version (int): Lock version of the ledger account.
        ledger_id (uuid|str): The id of the ledger that this account belongs to.
        ledgerable_id (uuid|str): If the ledger account links to another object in
            Modern Treasury, the id will be populated here, otherwise null.
        ledgerable_type (LedgerableTypeEnum): If the ledger account links to another
            object in Modern Treasury, the type will be populated here, otherwise
            null. The value is one of internal_account or external_account.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "name": "name",
        "description": "description",
        "normal_balance": "normal_balance",
        "balances": "balances",
        "lock_version": "lock_version",
        "ledger_id": "ledger_id",
        "ledgerable_id": "ledgerable_id",
        "ledgerable_type": "ledgerable_type",
        "metadata": "metadata",
    }

    _nullables = [
        "discarded_at",
        "description",
        "ledgerable_id",
        "ledgerable_type",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        name=None,
        description=None,
        normal_balance=None,
        balances=None,
        lock_version=None,
        ledger_id=None,
        ledgerable_id=None,
        ledgerable_type=None,
        metadata=None):
        """Initialize a LedgerAccount instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.name = name
        self.description = description
        self.normal_balance = normal_balance
        self.balances = balances
        self.lock_version = lock_version
        self.ledger_id = ledger_id
        self.ledgerable_id = ledgerable_id
        self.ledgerable_type = ledgerable_type
        self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        normal_balance =\
            dictionary.get("normal_balance")\
            if dictionary.get("normal_balance")\
                else None
        balances =\
            LedgerBalancesWithEffectiveAt.from_dictionary(
                dictionary.get("balances"))\
                if dictionary.get("balances") else None
        lock_version =\
            dictionary.get("lock_version")\
            if dictionary.get("lock_version")\
                else None
        ledger_id =\
            dictionary.get("ledger_id")\
            if dictionary.get("ledger_id")\
                else None
        ledgerable_id =\
            dictionary.get("ledgerable_id")\
            if dictionary.get("ledgerable_id")\
                else None
        ledgerable_type =\
            dictionary.get("ledgerable_type")\
            if dictionary.get("ledgerable_type")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   name,
                   description,
                   normal_balance,
                   balances,
                   lock_version,
                   ledger_id,
                   ledgerable_id,
                   ledgerable_type,
                   metadata)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _normal_balance=self.normal_balance
        _balances=self.balances
        _lock_version=self.lock_version
        _ledger_id=self.ledger_id
        _ledgerable_id=self.ledgerable_id
        _ledgerable_type=self.ledgerable_type
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"normal_balance={_normal_balance!r}, "
            f"balances={_balances!r}, "
            f"lock_version={_lock_version!r}, "
            f"ledger_id={_ledger_id!r}, "
            f"ledgerable_id={_ledgerable_id!r}, "
            f"ledgerable_type={_ledgerable_type!r}, "
            f"metadata={_metadata!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _normal_balance=self.normal_balance
        _balances=self.balances
        _lock_version=self.lock_version
        _ledger_id=self.ledger_id
        _ledgerable_id=self.ledgerable_id
        _ledgerable_type=self.ledgerable_type
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"normal_balance={_normal_balance!s}, "
            f"balances={_balances!s}, "
            f"lock_version={_lock_version!s}, "
            f"ledger_id={_ledger_id!s}, "
            f"ledgerable_id={_ledgerable_id!s}, "
            f"ledgerable_type={_ledgerable_type!s}, "
            f"metadata={_metadata!s}, "
            f")"
        )
