"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class LedgerEntryCreateRequest(object):
    """Implementation of the 'ledger_entry_create_request' model.

    Attributes:
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000. Can be any integer up to 36 digits.
        direction (Direction5): One of `credit`, `debit`. Describes the direction
            money is flowing in the transaction. A `credit` moves money from your
            account to someone else's. A `debit` pulls money from someone else's
            account to your own. Note that wire, rtp, and check payments will always
            be `credit`.
        ledger_account_id (uuid|str): The ledger account that this ledger entry is
            associated with.
        lock_version (int): Lock version of the ledger account. This can be passed
            when creating a ledger transaction to only succeed if no ledger
            transactions have posted since the given version. See our post about
            Designing the Ledgers API with Optimistic Locking for more details.
        pending_balance_amount (Dict[str, int]): Use `gt` (>), `gte` (>=), `lt` (<),
            `lte` (<=), or `eq` (=) to lock on the account’s pending balance. If any
            of these conditions would be false after the transaction is created, the
            entire call will fail with error code 422.
        posted_balance_amount (Dict[str, int]): Use `gt` (>), `gte` (>=), `lt` (<),
            `lte` (<=), or `eq` (=) to lock on the account’s posted balance. If any
            of these conditions would be false after the transaction is created, the
            entire call will fail with error code 422.
        available_balance_amount (Dict[str, int]): Use `gt` (>), `gte` (>=), `lt`
            (<), `lte` (<=), or `eq` (=) to lock on the account’s available balance.
            If any of these conditions would be false after the transaction is
            created, the entire call will fail with error code 422.
        show_resulting_ledger_account_balances (bool): If true, response will include
            the balance of the associated ledger account for the entry.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "direction": "direction",
        "ledger_account_id": "ledger_account_id",
        "lock_version": "lock_version",
        "pending_balance_amount": "pending_balance_amount",
        "posted_balance_amount": "posted_balance_amount",
        "available_balance_amount": "available_balance_amount",
        "show_resulting_ledger_account_balances":
            "show_resulting_ledger_account_balances",
        "metadata": "metadata",
    }

    _optionals = [
        "lock_version",
        "pending_balance_amount",
        "posted_balance_amount",
        "available_balance_amount",
        "show_resulting_ledger_account_balances",
        "metadata",
    ]

    _nullables = [
        "lock_version",
        "pending_balance_amount",
        "posted_balance_amount",
        "available_balance_amount",
        "show_resulting_ledger_account_balances",
    ]

    def __init__(
        self,
        amount=None,
        direction=None,
        ledger_account_id=None,
        lock_version=APIHelper.SKIP,
        pending_balance_amount=APIHelper.SKIP,
        posted_balance_amount=APIHelper.SKIP,
        available_balance_amount=APIHelper.SKIP,
        show_resulting_ledger_account_balances=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a LedgerEntryCreateRequest instance."""
        # Initialize members of the class
        self.amount = amount
        self.direction = direction
        self.ledger_account_id = ledger_account_id
        if lock_version is not APIHelper.SKIP:
            self.lock_version = lock_version
        if pending_balance_amount is not APIHelper.SKIP:
            self.pending_balance_amount = pending_balance_amount
        if posted_balance_amount is not APIHelper.SKIP:
            self.posted_balance_amount = posted_balance_amount
        if available_balance_amount is not APIHelper.SKIP:
            self.available_balance_amount = available_balance_amount
        if show_resulting_ledger_account_balances is not APIHelper.SKIP:
            self.show_resulting_ledger_account_balances =\
                 show_resulting_ledger_account_balances
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        ledger_account_id =\
            dictionary.get("ledger_account_id")\
            if dictionary.get("ledger_account_id")\
                else None
        lock_version =\
            dictionary.get("lock_version")\
            if "lock_version" in dictionary.keys()\
                else APIHelper.SKIP
        pending_balance_amount =\
            dictionary.get("pending_balance_amount")\
            if "pending_balance_amount" in dictionary.keys()\
                else APIHelper.SKIP
        posted_balance_amount =\
            dictionary.get("posted_balance_amount")\
            if "posted_balance_amount" in dictionary.keys()\
                else APIHelper.SKIP
        available_balance_amount =\
            dictionary.get("available_balance_amount")\
            if "available_balance_amount" in dictionary.keys()\
                else APIHelper.SKIP
        show_resulting_ledger_account_balances =\
            dictionary.get("show_resulting_ledger_account_balances")\
            if "show_resulting_ledger_account_balances" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(amount,
                   direction,
                   ledger_account_id,
                   lock_version,
                   pending_balance_amount,
                   posted_balance_amount,
                   available_balance_amount,
                   show_resulting_ledger_account_balances,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=self.amount
        _direction=self.direction
        _ledger_account_id=self.ledger_account_id
        _lock_version=(
            self.lock_version
            if hasattr(self, "lock_version")
            else None
        )
        _pending_balance_amount=(
            self.pending_balance_amount
            if hasattr(self, "pending_balance_amount")
            else None
        )
        _posted_balance_amount=(
            self.posted_balance_amount
            if hasattr(self, "posted_balance_amount")
            else None
        )
        _available_balance_amount=(
            self.available_balance_amount
            if hasattr(self, "available_balance_amount")
            else None
        )
        _show_resulting_ledger_account_balances=(
            self.show_resulting_ledger_account_balances
            if hasattr(self, "show_resulting_ledger_account_balances")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"direction={_direction!r}, "
            f"ledger_account_id={_ledger_account_id!r}, "
            f"lock_version={_lock_version!r}, "
            f"pending_balance_amount={_pending_balance_amount!r}, "
            f"posted_balance_amount={_posted_balance_amount!r}, "
            f"available_balance_amount={_available_balance_amount!r}, "
            f"show_resulting_ledger_account_balances={_show_resulting_ledger_account_balances!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=self.amount
        _direction=self.direction
        _ledger_account_id=self.ledger_account_id
        _lock_version=(
            self.lock_version
            if hasattr(self, "lock_version")
            else None
        )
        _pending_balance_amount=(
            self.pending_balance_amount
            if hasattr(self, "pending_balance_amount")
            else None
        )
        _posted_balance_amount=(
            self.posted_balance_amount
            if hasattr(self, "posted_balance_amount")
            else None
        )
        _available_balance_amount=(
            self.available_balance_amount
            if hasattr(self, "available_balance_amount")
            else None
        )
        _show_resulting_ledger_account_balances=(
            self.show_resulting_ledger_account_balances
            if hasattr(self, "show_resulting_ledger_account_balances")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"direction={_direction!s}, "
            f"ledger_account_id={_ledger_account_id!s}, "
            f"lock_version={_lock_version!s}, "
            f"pending_balance_amount={_pending_balance_amount!s}, "
            f"posted_balance_amount={_posted_balance_amount!s}, "
            f"available_balance_amount={_available_balance_amount!s}, "
            f"show_resulting_ledger_account_balances={_show_resulting_ledger_account_balances!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
