"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class LegacyDocumentCreateRequest(object):
    """Implementation of the 'legacy_document_create_request' model.

    Attributes:
        document_type (str): A category given to the document, can be `null`.
        file (binary): The model property of type binary.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "file": "file",
        "document_type": "document_type",
    }

    _optionals = [
        "document_type",
    ]

    def __init__(
        self,
        file=None,
        document_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a LegacyDocumentCreateRequest instance."""
        # Initialize members of the class
        if document_type is not APIHelper.SKIP:
            self.document_type = document_type
        self.file = file

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        file =\
            dictionary.get("file")\
            if dictionary.get("file")\
                else None
        document_type =\
            dictionary.get("document_type")\
            if dictionary.get("document_type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(file,
                   document_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _document_type=(
            self.document_type
            if hasattr(self, "document_type")
            else None
        )
        _file=self.file
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"document_type={_document_type!r}, "
            f"file={_file!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _document_type=(
            self.document_type
            if hasattr(self, "document_type")
            else None
        )
        _file=self.file
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"document_type={_document_type!s}, "
            f"file={_file!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
