"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class LineItemRequest(object):
    """Implementation of the 'line_item_request' model.

    Attributes:
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        description (str): A free-form description of the line item.
        accounting_category_id (str): The ID of one of your accounting categories.
            Note that these will only be accessible if your accounting system has
            been connected.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "metadata": "metadata",
        "description": "description",
        "accounting_category_id": "accounting_category_id",
    }

    _optionals = [
        "metadata",
        "description",
        "accounting_category_id",
    ]

    _nullables = [
        "description",
        "accounting_category_id",
    ]

    def __init__(
        self,
        amount=None,
        metadata=APIHelper.SKIP,
        description=APIHelper.SKIP,
        accounting_category_id=APIHelper.SKIP):
        """Initialize a LineItemRequest instance."""
        # Initialize members of the class
        self.amount = amount
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if description is not APIHelper.SKIP:
            self.description = description
        if accounting_category_id is not APIHelper.SKIP:
            self.accounting_category_id = accounting_category_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        accounting_category_id =\
            dictionary.get("accounting_category_id")\
            if "accounting_category_id" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(amount,
                   metadata,
                   description,
                   accounting_category_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=self.amount
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _accounting_category_id=(
            self.accounting_category_id
            if hasattr(self, "accounting_category_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"metadata={_metadata!r}, "
            f"description={_description!r}, "
            f"accounting_category_id={_accounting_category_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=self.amount
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _accounting_category_id=(
            self.accounting_category_id
            if hasattr(self, "accounting_category_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"metadata={_metadata!s}, "
            f"description={_description!s}, "
            f"accounting_category_id={_accounting_category_id!s}, "
            f")"
        )
