"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PaymentFlowCreateRequest(object):
    """Implementation of the 'payment_flow_create_request' model.

    Attributes:
        amount (int): Required. Value in specified currency's smallest unit. e.g. $10
            would be represented as 1000. Can be any integer up to 36 digits.
        currency (str): Required. The currency of the payment.
        direction (Direction10Enum): Required. Describes the direction money is
            flowing in the transaction. Can only be `debit`. A `debit` pulls money
            from someone else's account to your own.
        counterparty_id (uuid|str): Required. The ID of a counterparty associated
            with the payment. As part of the payment workflow an external account
            will be associated with this model.
        originating_account_id (uuid|str): Required. The ID of one of your
            organization's internal accounts.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "currency": "currency",
        "direction": "direction",
        "counterparty_id": "counterparty_id",
        "originating_account_id": "originating_account_id",
    }

    def __init__(
        self,
        amount=None,
        currency=None,
        direction=None,
        counterparty_id=None,
        originating_account_id=None):
        """Initialize a PaymentFlowCreateRequest instance."""
        # Initialize members of the class
        self.amount = amount
        self.currency = currency
        self.direction = direction
        self.counterparty_id = counterparty_id
        self.originating_account_id = originating_account_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else None
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if dictionary.get("counterparty_id")\
                else None
        originating_account_id =\
            dictionary.get("originating_account_id")\
            if dictionary.get("originating_account_id")\
                else None

        # Return an object of this model
        return cls(amount,
                   currency,
                   direction,
                   counterparty_id,
                   originating_account_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=self.amount
        _currency=self.currency
        _direction=self.direction
        _counterparty_id=self.counterparty_id
        _originating_account_id=self.originating_account_id
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"direction={_direction!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"originating_account_id={_originating_account_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=self.amount
        _currency=self.currency
        _direction=self.direction
        _counterparty_id=self.counterparty_id
        _originating_account_id=self.originating_account_id
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"direction={_direction!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"originating_account_id={_originating_account_id!s}, "
            f")"
        )
