"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PaymentFlowUpdateRequest(object):
    """Implementation of the 'payment_flow_update_request' model.

    Attributes:
        status (str): Required. The updated status of the payment flow. Can only be
            used to mark a flow as `cancelled`.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
    }

    def __init__(
        self,
):
        """Initialize a PaymentFlowUpdateRequest instance."""
        # Initialize members of the class
        self.status = "cancelled"

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary

        # Return an object of this model
        return cls()

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f")"
        )
