"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentType13(object):
    """Implementation of the 'payment_type13' enum.

    Attributes:
        ACH: The enum member of type str.
        AU_BECS: The enum member of type str.
        BACS: The enum member of type str.
        BOOK: The enum member of type str.
        CARD: The enum member of type str.
        CHECK: The enum member of type str.
        CROSS_BORDER: The enum member of type str.
        EFT: The enum member of type str.
        INTERAC: The enum member of type str.
        MASAV: The enum member of type str.
        NEFT: The enum member of type str.
        PROVXCHANGE: The enum member of type str.
        RTP: The enum member of type str.
        SEN: The enum member of type str.
        SEPA: The enum member of type str.
        SIGNET: The enum member of type str.
        WIRE: The enum member of type str.

    """

    _all_values = ["ach", "au_becs", "bacs", "book", "card", "check",
        "cross_border", "eft", "interac", "masav", "neft", "provxchange", "rtp",
        "sen", "sepa", "signet", "wire"]
    ACH = "ach"

    AU_BECS = "au_becs"

    BACS = "bacs"

    BOOK = "book"

    CARD = "card"

    CHECK = "check"

    CROSS_BORDER = "cross_border"

    EFT = "eft"

    INTERAC = "interac"

    MASAV = "masav"

    NEFT = "neft"

    PROVXCHANGE = "provxchange"

    RTP = "rtp"

    SEN = "sen"

    SEPA = "sepa"

    SIGNET = "signet"

    WIRE = "wire"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
