"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from datetime import date

import dateutil.parser

from moderntreasury.api_helper import APIHelper
from moderntreasury.models.accounting import (
    Accounting,
)
from moderntreasury.models.charge_bearer_enum import (
    ChargeBearerEnum,
)
from moderntreasury.models.currency_enum import (
    CurrencyEnum,
)
from moderntreasury.models.direction_5_enum import (
    Direction5Enum,
)
from moderntreasury.models.foreign_exchange_indicator_enum import (
    ForeignExchangeIndicatorEnum,
)
from moderntreasury.models.mreturn import Return
from moderntreasury.models.payment_reference import (
    PaymentReference,
)
from moderntreasury.models.priority_enum import (
    PriorityEnum,
)
from moderntreasury.models.receiving_account_type_enum import (
    ReceivingAccountTypeEnum,
)
from moderntreasury.models.status_3_enum import (
    Status3Enum,
)
from moderntreasury.models.subtype_enum import (
    SubtypeEnum,
)
from moderntreasury.models.type_5_enum import (
    Type5Enum,
)


class PaymentOrder(object):
    """Implementation of the 'payment_order' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        mtype (Type5Enum): One of `ach`, `eft`, `wire`, `check`, `sen`, `book`,
            `rtp`, `sepa`, `bacs`, `au_becs`, `interac`, `signet`, `provexchange`.
        subtype (SubtypeEnum): An additional layer of classification for the type of
            payment order you are doing. This field is only used for `ach` payment
            orders currently. For `ach`  payment orders, the `subtype`  represents
            the SEC code. We currently support `CCD`, `PPD`, `IAT`, `CTX`, `WEB`,
            `CIE`, and `TEL`.
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000 (cents). For RTP, the maximum amount allowed by the
            network is $100,000.
        direction (Direction5Enum): One of `credit`, `debit`. Describes the direction
            money is flowing in the transaction. A `credit` moves money from your
            account to someone else's. A `debit` pulls money from someone else's
            account to your own. Note that wire, rtp, and check payments will always
            be `credit`.
        priority (PriorityEnum): Either `normal` or `high`. For ACH and EFT payments,
            `high` represents a same-day ACH or EFT transfer, respectively. For check
            payments, `high` can mean an overnight check rather than standard mail.
        originating_account_id (uuid|str): The ID of one of your organization's
            internal accounts.
        receiving_account_id (uuid|str): The receiving account ID. Can be an
            `external_account` or `internal_account`.
        accounting (Accounting): The model property of type Accounting.
        accounting_category_id (uuid|str): The ID of one of your accounting
            categories. Note that these will only be accessible if your accounting
            system has been connected.
        accounting_ledger_class_id (uuid|str): The ID of one of your accounting
            ledger classes. Note that these will only be accessible if your
            accounting system has been connected.
        currency (CurrencyEnum): Three-letter ISO currency code.
        effective_date (date): Date transactions are to be posted to the
            participants' account. Defaults to the current business day or the next
            business day if the current day is a bank holiday or weekend. Format:
            yyyy-mm-dd.
        description (str): An optional description for internal use.
        statement_descriptor (str): An optional descriptor which will appear in the
            receiver's statement. For `check` payments this field will be used as the
            memo line. For `ach` the maximum length is 10 characters. Note that for
            ACH payments, the name on your bank account will be included
            automatically by the bank, so you can use the characters for other useful
            information. For `eft` the maximum length is 15 characters.
        remittance_information (str): For `ach`, this field will be passed through on
            an addenda record. For `wire` payments the field will be passed through
            as the "Originator to Beneficiary Information", also known as OBI or
            Fedwire tag 6000.
        purpose (str): For `wire`, this is usually the purpose which is transmitted
            via the "InstrForDbtrAgt" field in the ISO20022 file. If you are using
            Currencycloud, this is the `payment.purpose_code` field. For `eft`, this
            field is the 3 digit CPA Code that will be attached to the payment.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        charge_bearer (ChargeBearerEnum): The party that will pay the fees for the
            payment order. Only applies to wire payment orders. Can be one of shared,
            sender, or receiver, which correspond respectively with the SWIFT 71A
            values `SHA`, `OUR`, `BEN`.
        foreign_exchange_indicator (ForeignExchangeIndicatorEnum): Indicates the type
            of FX transfer to initiate, can be either `variable_to_fixed`,
            `fixed_to_variable`, or `null` if the payment order currency matches the
            originating account currency.
        foreign_exchange_contract (str): If present, indicates a specific foreign
            exchange contract number that has been generated by your financial
            institution.
        nsf_protected (bool): A boolean to determine if NSF Protection is enabled for
            this payment order. Note that this setting must also be turned on in your
            organization settings page.
        originating_party_name (str): If present, this will replace your default
            company name on receiver's bank statement. This field can only be used
            for ACH payments currently. For ACH, only the first 16 characters of this
            string will be used. Any additional characters will be truncated.
        ultimate_originating_party_name (str): Name of the ultimate originator of the
            payment order.
        ultimate_originating_party_identifier (str): Identifier of the ultimate
            originator of the payment order.
        ultimate_receiving_party_name (str): The model property of type str.
        ultimate_receiving_party_identifier (str): The model property of type str.
        send_remittance_advice (bool): Send an email to the counterparty when the
            payment order is sent to the bank. If `null`, `send_remittance_advice` on
            the Counterparty is used.
        expires_at (datetime): RFP payments require an expires_at. This value must be
            past the effective_date.
        status (Status3Enum): The current status of the payment order.
        receiving_account (ReceivingAccount | InternalAccount | None): The receiving
            account. Can be an `external_account` or `internal_account`.
        receiving_account_type (ReceivingAccountTypeEnum): The model property of type
            ReceivingAccountTypeEnum.
        counterparty_id (uuid|str): If the payment order is tied to a specific
            Counterparty, their id will appear, otherwise `null`.
        transaction_ids (List[uuid|str]): The IDs of all the transactions associated
            to this payment order. Usually, you will only have a single transaction
            ID. However, if a payment order initially results in a Return, but gets
            redrafted and is later successfully completed, it can have many
            transactions.
        ledger_transaction_id (uuid|str): The ID of the ledger transaction linked to
            the payment order.
        current_return (Return): The model property of type Return.
        transaction_monitoring_enabled (bool): A flag that determines whether a
            payment order should go through transaction monitoring.
        compliance_rule_metadata (Any): Custom key-value pair for usage in compliance
            rules. Please contact support before making changes to this field.
        reference_numbers (List[PaymentReference]): The model property of type
            List[PaymentReference].
        vendor_failure_reason (str): This field will be populated if a vendor (e.g.
            Currencycloud) failure occurs. Logic shouldn't be built on its value as
            it is free-form.
        decision_id (uuid|str): The ID of the compliance decision for the payment
            order, if transaction monitoring is enabled.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "mtype": "type",
        "subtype": "subtype",
        "amount": "amount",
        "direction": "direction",
        "priority": "priority",
        "originating_account_id": "originating_account_id",
        "receiving_account_id": "receiving_account_id",
        "accounting": "accounting",
        "accounting_category_id": "accounting_category_id",
        "accounting_ledger_class_id": "accounting_ledger_class_id",
        "currency": "currency",
        "effective_date": "effective_date",
        "description": "description",
        "statement_descriptor": "statement_descriptor",
        "remittance_information": "remittance_information",
        "purpose": "purpose",
        "metadata": "metadata",
        "charge_bearer": "charge_bearer",
        "foreign_exchange_indicator": "foreign_exchange_indicator",
        "foreign_exchange_contract": "foreign_exchange_contract",
        "nsf_protected": "nsf_protected",
        "originating_party_name": "originating_party_name",
        "ultimate_originating_party_name": "ultimate_originating_party_name",
        "ultimate_originating_party_identifier":
            "ultimate_originating_party_identifier",
        "ultimate_receiving_party_name": "ultimate_receiving_party_name",
        "ultimate_receiving_party_identifier": "ultimate_receiving_party_identifier",
        "send_remittance_advice": "send_remittance_advice",
        "expires_at": "expires_at",
        "status": "status",
        "receiving_account": "receiving_account",
        "receiving_account_type": "receiving_account_type",
        "counterparty_id": "counterparty_id",
        "transaction_ids": "transaction_ids",
        "ledger_transaction_id": "ledger_transaction_id",
        "current_return": "current_return",
        "transaction_monitoring_enabled": "transaction_monitoring_enabled",
        "compliance_rule_metadata": "compliance_rule_metadata",
        "reference_numbers": "reference_numbers",
        "vendor_failure_reason": "vendor_failure_reason",
        "decision_id": "decision_id",
    }

    _nullables = [
        "subtype",
        "accounting_category_id",
        "accounting_ledger_class_id",
        "description",
        "statement_descriptor",
        "remittance_information",
        "purpose",
        "charge_bearer",
        "foreign_exchange_indicator",
        "foreign_exchange_contract",
        "originating_party_name",
        "ultimate_originating_party_name",
        "ultimate_originating_party_identifier",
        "ultimate_receiving_party_name",
        "ultimate_receiving_party_identifier",
        "send_remittance_advice",
        "expires_at",
        "receiving_account",
        "counterparty_id",
        "ledger_transaction_id",
        "compliance_rule_metadata",
        "vendor_failure_reason",
        "decision_id",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        mtype=None,
        subtype=None,
        amount=None,
        direction=None,
        priority=None,
        originating_account_id=None,
        receiving_account_id=None,
        accounting=None,
        accounting_category_id=None,
        accounting_ledger_class_id=None,
        currency=None,
        effective_date=None,
        description=None,
        statement_descriptor=None,
        remittance_information=None,
        purpose=None,
        metadata=None,
        charge_bearer=None,
        foreign_exchange_indicator=None,
        foreign_exchange_contract=None,
        nsf_protected=None,
        originating_party_name=None,
        ultimate_originating_party_name=None,
        ultimate_originating_party_identifier=None,
        ultimate_receiving_party_name=None,
        ultimate_receiving_party_identifier=None,
        send_remittance_advice=None,
        expires_at=None,
        status=None,
        receiving_account=None,
        receiving_account_type=None,
        counterparty_id=None,
        transaction_ids=None,
        ledger_transaction_id=None,
        current_return=None,
        transaction_monitoring_enabled=None,
        compliance_rule_metadata=None,
        reference_numbers=None,
        vendor_failure_reason=None,
        decision_id=None):
        """Initialize a PaymentOrder instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.mtype = mtype
        self.subtype = subtype
        self.amount = amount
        self.direction = direction
        self.priority = priority
        self.originating_account_id = originating_account_id
        self.receiving_account_id = receiving_account_id
        self.accounting = accounting
        self.accounting_category_id = accounting_category_id
        self.accounting_ledger_class_id = accounting_ledger_class_id
        self.currency = currency
        self.effective_date = effective_date
        self.description = description
        self.statement_descriptor = statement_descriptor
        self.remittance_information = remittance_information
        self.purpose = purpose
        self.metadata = metadata
        self.charge_bearer = charge_bearer
        self.foreign_exchange_indicator = foreign_exchange_indicator
        self.foreign_exchange_contract = foreign_exchange_contract
        self.nsf_protected = nsf_protected
        self.originating_party_name = originating_party_name
        self.ultimate_originating_party_name = ultimate_originating_party_name
        self.ultimate_originating_party_identifier =\
             ultimate_originating_party_identifier
        self.ultimate_receiving_party_name = ultimate_receiving_party_name
        self.ultimate_receiving_party_identifier =\
             ultimate_receiving_party_identifier
        self.send_remittance_advice = send_remittance_advice
        self.expires_at =\
             APIHelper.apply_datetime_converter(
            expires_at, APIHelper.RFC3339DateTime)\
             if expires_at else None
        self.status = status
        self.receiving_account = receiving_account
        self.receiving_account_type = receiving_account_type
        self.counterparty_id = counterparty_id
        self.transaction_ids = transaction_ids
        self.ledger_transaction_id = ledger_transaction_id
        self.current_return = current_return
        self.transaction_monitoring_enabled = transaction_monitoring_enabled
        self.compliance_rule_metadata = compliance_rule_metadata
        self.reference_numbers = reference_numbers
        self.vendor_failure_reason = vendor_failure_reason
        self.decision_id = decision_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from moderntreasury.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        subtype =\
            dictionary.get("subtype")\
            if dictionary.get("subtype")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        priority =\
            dictionary.get("priority")\
            if dictionary.get("priority")\
                else None
        originating_account_id =\
            dictionary.get("originating_account_id")\
            if dictionary.get("originating_account_id")\
                else None
        receiving_account_id =\
            dictionary.get("receiving_account_id")\
            if dictionary.get("receiving_account_id")\
                else None
        accounting =\
            Accounting.from_dictionary(
                dictionary.get("accounting"))\
                if dictionary.get("accounting") else None
        accounting_category_id =\
            dictionary.get("accounting_category_id")\
            if dictionary.get("accounting_category_id")\
                else None
        accounting_ledger_class_id =\
            dictionary.get("accounting_ledger_class_id")\
            if dictionary.get("accounting_ledger_class_id")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else None
        effective_date = dateutil.parser.parse(
            dictionary.get("effective_date")).date()\
            if dictionary.get("effective_date") else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        statement_descriptor =\
            dictionary.get("statement_descriptor")\
            if dictionary.get("statement_descriptor")\
                else None
        remittance_information =\
            dictionary.get("remittance_information")\
            if dictionary.get("remittance_information")\
                else None
        purpose =\
            dictionary.get("purpose")\
            if dictionary.get("purpose")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None
        charge_bearer =\
            dictionary.get("charge_bearer")\
            if dictionary.get("charge_bearer")\
                else None
        foreign_exchange_indicator =\
            dictionary.get("foreign_exchange_indicator")\
            if dictionary.get("foreign_exchange_indicator")\
                else None
        foreign_exchange_contract =\
            dictionary.get("foreign_exchange_contract")\
            if dictionary.get("foreign_exchange_contract")\
                else None
        nsf_protected =\
            dictionary.get("nsf_protected")\
            if "nsf_protected" in dictionary.keys()\
                else None
        originating_party_name =\
            dictionary.get("originating_party_name")\
            if dictionary.get("originating_party_name")\
                else None
        ultimate_originating_party_name =\
            dictionary.get("ultimate_originating_party_name")\
            if dictionary.get("ultimate_originating_party_name")\
                else None
        ultimate_originating_party_identifier =\
            dictionary.get("ultimate_originating_party_identifier")\
            if dictionary.get("ultimate_originating_party_identifier")\
                else None
        ultimate_receiving_party_name =\
            dictionary.get("ultimate_receiving_party_name")\
            if dictionary.get("ultimate_receiving_party_name")\
                else None
        ultimate_receiving_party_identifier =\
            dictionary.get("ultimate_receiving_party_identifier")\
            if dictionary.get("ultimate_receiving_party_identifier")\
                else None
        send_remittance_advice =\
            dictionary.get("send_remittance_advice")\
            if "send_remittance_advice" in dictionary.keys()\
                else None
        expires_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expires_at")).datetime\
            if dictionary.get("expires_at") else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        receiving_account = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PaymentOrderReceivingAccount"),
            dictionary.get("receiving_account"),
            False)\
            if dictionary.get("receiving_account") is not None\
            else None
        receiving_account_type =\
            dictionary.get("receiving_account_type")\
            if dictionary.get("receiving_account_type")\
                else None
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if dictionary.get("counterparty_id")\
                else None
        transaction_ids =\
            dictionary.get("transaction_ids")\
            if dictionary.get("transaction_ids")\
                else None
        ledger_transaction_id =\
            dictionary.get("ledger_transaction_id")\
            if dictionary.get("ledger_transaction_id")\
                else None
        current_return =\
            Return.from_dictionary(
                dictionary.get("current_return"))\
                if dictionary.get("current_return") else None
        transaction_monitoring_enabled =\
            dictionary.get("transaction_monitoring_enabled")\
            if "transaction_monitoring_enabled" in dictionary.keys()\
                else None
        compliance_rule_metadata =\
            dictionary.get("compliance_rule_metadata")\
            if dictionary.get("compliance_rule_metadata")\
                else None
        reference_numbers = None
        if dictionary.get("reference_numbers") is not None:
            reference_numbers = [
                PaymentReference.from_dictionary(x)
                    for x in dictionary.get("reference_numbers")
            ]
        vendor_failure_reason =\
            dictionary.get("vendor_failure_reason")\
            if dictionary.get("vendor_failure_reason")\
                else None
        decision_id =\
            dictionary.get("decision_id")\
            if dictionary.get("decision_id")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   mtype,
                   subtype,
                   amount,
                   direction,
                   priority,
                   originating_account_id,
                   receiving_account_id,
                   accounting,
                   accounting_category_id,
                   accounting_ledger_class_id,
                   currency,
                   effective_date,
                   description,
                   statement_descriptor,
                   remittance_information,
                   purpose,
                   metadata,
                   charge_bearer,
                   foreign_exchange_indicator,
                   foreign_exchange_contract,
                   nsf_protected,
                   originating_party_name,
                   ultimate_originating_party_name,
                   ultimate_originating_party_identifier,
                   ultimate_receiving_party_name,
                   ultimate_receiving_party_identifier,
                   send_remittance_advice,
                   expires_at,
                   status,
                   receiving_account,
                   receiving_account_type,
                   counterparty_id,
                   transaction_ids,
                   ledger_transaction_id,
                   current_return,
                   transaction_monitoring_enabled,
                   compliance_rule_metadata,
                   reference_numbers,
                   vendor_failure_reason,
                   decision_id)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from moderntreasury.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.object,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.live_mode,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.created_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.updated_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type5Enum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.subtype,
                    type_callable=lambda value:
                        SubtypeEnum.validate(value),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.amount,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.direction,
                    type_callable=lambda value:
                        Direction5Enum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.priority,
                    type_callable=lambda value:
                        PriorityEnum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.originating_account_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.receiving_account_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.accounting,
                    type_callable=lambda value:
                        Accounting.validate(value),
                    is_model_dict=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.accounting_category_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.accounting_ledger_class_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.currency,
                    type_callable=lambda value:
                        CurrencyEnum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.effective_date,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        date,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.description,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.statement_descriptor,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.remittance_information,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.purpose,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.metadata,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.charge_bearer,
                    type_callable=lambda value:
                        ChargeBearerEnum.validate(value),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.foreign_exchange_indicator,
                    type_callable=lambda value:
                        ForeignExchangeIndicatorEnum.validate(value),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.foreign_exchange_contract,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.nsf_protected,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.originating_party_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.ultimate_originating_party_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.ultimate_originating_party_identifier,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.ultimate_receiving_party_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.ultimate_receiving_party_identifier,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.send_remittance_advice,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.expires_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.status,
                    type_callable=lambda value:
                        Status3Enum.validate(value)) \
                and (UnionTypeLookUp.get("PaymentOrderReceivingAccount")
                .validate(dictionary.receiving_account).is_valid) \
                and APIHelper.is_valid_type(
                    value=dictionary.receiving_account_type,
                    type_callable=lambda value:
                        ReceivingAccountTypeEnum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.counterparty_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.transaction_ids,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.ledger_transaction_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.current_return,
                    type_callable=lambda value:
                        Return.validate(value),
                    is_model_dict=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.transaction_monitoring_enabled,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.compliance_rule_metadata,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        Any,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.reference_numbers,
                    type_callable=lambda value:
                        PaymentReference.validate(value),
                    is_model_dict=True,
                    is_inner_model_dict=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.vendor_failure_reason,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.decision_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("object"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("live_mode"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("created_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("updated_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type5Enum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("subtype"),
                type_callable=lambda value:
                    SubtypeEnum.validate(value),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("amount"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("direction"),
                type_callable=lambda value:
                    Direction5Enum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("priority"),
                type_callable=lambda value:
                    PriorityEnum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("originating_account_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("receiving_account_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("accounting"),
                type_callable=lambda value:
                    Accounting.validate(value),
                is_model_dict=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("accounting_category_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("accounting_ledger_class_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("currency"),
                type_callable=lambda value:
                    CurrencyEnum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("effective_date"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("description"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("statement_descriptor"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("remittance_information"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("purpose"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("metadata"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("charge_bearer"),
                type_callable=lambda value:
                    ChargeBearerEnum.validate(value),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("foreign_exchange_indicator"),
                type_callable=lambda value:
                    ForeignExchangeIndicatorEnum.validate(value),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("foreign_exchange_contract"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("nsf_protected"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("originating_party_name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("ultimate_originating_party_name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("ultimate_originating_party_identifier"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("ultimate_receiving_party_name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("ultimate_receiving_party_identifier"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("send_remittance_advice"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("expires_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("status"),
                type_callable=lambda value:
                    Status3Enum.validate(value)) \
            and (UnionTypeLookUp.get("PaymentOrderReceivingAccount")
            .validate(dictionary.get("receiving_account")).is_valid) \
            and APIHelper.is_valid_type(
                value=dictionary.get("receiving_account_type"),
                type_callable=lambda value:
                    ReceivingAccountTypeEnum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("counterparty_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("transaction_ids"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("ledger_transaction_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("current_return"),
                type_callable=lambda value:
                    Return.validate(value),
                is_model_dict=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("transaction_monitoring_enabled"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("compliance_rule_metadata"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    Any,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("reference_numbers"),
                type_callable=lambda value:
                    PaymentReference.validate(value),
                is_model_dict=True,
                is_inner_model_dict=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("vendor_failure_reason"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("decision_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _mtype=self.mtype
        _subtype=self.subtype
        _amount=self.amount
        _direction=self.direction
        _priority=self.priority
        _originating_account_id=self.originating_account_id
        _receiving_account_id=self.receiving_account_id
        _accounting=self.accounting
        _accounting_category_id=self.accounting_category_id
        _accounting_ledger_class_id=self.accounting_ledger_class_id
        _currency=self.currency
        _effective_date=self.effective_date
        _description=self.description
        _statement_descriptor=self.statement_descriptor
        _remittance_information=self.remittance_information
        _purpose=self.purpose
        _metadata=self.metadata
        _charge_bearer=self.charge_bearer
        _foreign_exchange_indicator=self.foreign_exchange_indicator
        _foreign_exchange_contract=self.foreign_exchange_contract
        _nsf_protected=self.nsf_protected
        _originating_party_name=self.originating_party_name
        _ultimate_originating_party_name=self.ultimate_originating_party_name
        _ultimate_originating_party_identifier=self.ultimate_originating_party_identifier
        _ultimate_receiving_party_name=self.ultimate_receiving_party_name
        _ultimate_receiving_party_identifier=self.ultimate_receiving_party_identifier
        _send_remittance_advice=self.send_remittance_advice
        _expires_at=self.expires_at
        _status=self.status
        _receiving_account=self.receiving_account
        _receiving_account_type=self.receiving_account_type
        _counterparty_id=self.counterparty_id
        _transaction_ids=self.transaction_ids
        _ledger_transaction_id=self.ledger_transaction_id
        _current_return=self.current_return
        _transaction_monitoring_enabled=self.transaction_monitoring_enabled
        _compliance_rule_metadata=self.compliance_rule_metadata
        _reference_numbers=self.reference_numbers
        _vendor_failure_reason=self.vendor_failure_reason
        _decision_id=self.decision_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"mtype={_mtype!r}, "
            f"subtype={_subtype!r}, "
            f"amount={_amount!r}, "
            f"direction={_direction!r}, "
            f"priority={_priority!r}, "
            f"originating_account_id={_originating_account_id!r}, "
            f"receiving_account_id={_receiving_account_id!r}, "
            f"accounting={_accounting!r}, "
            f"accounting_category_id={_accounting_category_id!r}, "
            f"accounting_ledger_class_id={_accounting_ledger_class_id!r}, "
            f"currency={_currency!r}, "
            f"effective_date={_effective_date!r}, "
            f"description={_description!r}, "
            f"statement_descriptor={_statement_descriptor!r}, "
            f"remittance_information={_remittance_information!r}, "
            f"purpose={_purpose!r}, "
            f"metadata={_metadata!r}, "
            f"charge_bearer={_charge_bearer!r}, "
            f"foreign_exchange_indicator={_foreign_exchange_indicator!r}, "
            f"foreign_exchange_contract={_foreign_exchange_contract!r}, "
            f"nsf_protected={_nsf_protected!r}, "
            f"originating_party_name={_originating_party_name!r}, "
            f"ultimate_originating_party_name={_ultimate_originating_party_name!r}, "
            f"ultimate_originating_party_identifier={_ultimate_originating_party_identifier!r}, "
            f"ultimate_receiving_party_name={_ultimate_receiving_party_name!r}, "
            f"ultimate_receiving_party_identifier={_ultimate_receiving_party_identifier!r}, "
            f"send_remittance_advice={_send_remittance_advice!r}, "
            f"expires_at={_expires_at!r}, "
            f"status={_status!r}, "
            f"receiving_account={_receiving_account!r}, "
            f"receiving_account_type={_receiving_account_type!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"transaction_ids={_transaction_ids!r}, "
            f"ledger_transaction_id={_ledger_transaction_id!r}, "
            f"current_return={_current_return!r}, "
            f"transaction_monitoring_enabled={_transaction_monitoring_enabled!r}, "
            f"compliance_rule_metadata={_compliance_rule_metadata!r}, "
            f"reference_numbers={_reference_numbers!r}, "
            f"vendor_failure_reason={_vendor_failure_reason!r}, "
            f"decision_id={_decision_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _mtype=self.mtype
        _subtype=self.subtype
        _amount=self.amount
        _direction=self.direction
        _priority=self.priority
        _originating_account_id=self.originating_account_id
        _receiving_account_id=self.receiving_account_id
        _accounting=self.accounting
        _accounting_category_id=self.accounting_category_id
        _accounting_ledger_class_id=self.accounting_ledger_class_id
        _currency=self.currency
        _effective_date=self.effective_date
        _description=self.description
        _statement_descriptor=self.statement_descriptor
        _remittance_information=self.remittance_information
        _purpose=self.purpose
        _metadata=self.metadata
        _charge_bearer=self.charge_bearer
        _foreign_exchange_indicator=self.foreign_exchange_indicator
        _foreign_exchange_contract=self.foreign_exchange_contract
        _nsf_protected=self.nsf_protected
        _originating_party_name=self.originating_party_name
        _ultimate_originating_party_name=self.ultimate_originating_party_name
        _ultimate_originating_party_identifier=self.ultimate_originating_party_identifier
        _ultimate_receiving_party_name=self.ultimate_receiving_party_name
        _ultimate_receiving_party_identifier=self.ultimate_receiving_party_identifier
        _send_remittance_advice=self.send_remittance_advice
        _expires_at=self.expires_at
        _status=self.status
        _receiving_account=self.receiving_account
        _receiving_account_type=self.receiving_account_type
        _counterparty_id=self.counterparty_id
        _transaction_ids=self.transaction_ids
        _ledger_transaction_id=self.ledger_transaction_id
        _current_return=self.current_return
        _transaction_monitoring_enabled=self.transaction_monitoring_enabled
        _compliance_rule_metadata=self.compliance_rule_metadata
        _reference_numbers=self.reference_numbers
        _vendor_failure_reason=self.vendor_failure_reason
        _decision_id=self.decision_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"mtype={_mtype!s}, "
            f"subtype={_subtype!s}, "
            f"amount={_amount!s}, "
            f"direction={_direction!s}, "
            f"priority={_priority!s}, "
            f"originating_account_id={_originating_account_id!s}, "
            f"receiving_account_id={_receiving_account_id!s}, "
            f"accounting={_accounting!s}, "
            f"accounting_category_id={_accounting_category_id!s}, "
            f"accounting_ledger_class_id={_accounting_ledger_class_id!s}, "
            f"currency={_currency!s}, "
            f"effective_date={_effective_date!s}, "
            f"description={_description!s}, "
            f"statement_descriptor={_statement_descriptor!s}, "
            f"remittance_information={_remittance_information!s}, "
            f"purpose={_purpose!s}, "
            f"metadata={_metadata!s}, "
            f"charge_bearer={_charge_bearer!s}, "
            f"foreign_exchange_indicator={_foreign_exchange_indicator!s}, "
            f"foreign_exchange_contract={_foreign_exchange_contract!s}, "
            f"nsf_protected={_nsf_protected!s}, "
            f"originating_party_name={_originating_party_name!s}, "
            f"ultimate_originating_party_name={_ultimate_originating_party_name!s}, "
            f"ultimate_originating_party_identifier={_ultimate_originating_party_identifier!s}, "
            f"ultimate_receiving_party_name={_ultimate_receiving_party_name!s}, "
            f"ultimate_receiving_party_identifier={_ultimate_receiving_party_identifier!s}, "
            f"send_remittance_advice={_send_remittance_advice!s}, "
            f"expires_at={_expires_at!s}, "
            f"status={_status!s}, "
            f"receiving_account={_receiving_account!s}, "
            f"receiving_account_type={_receiving_account_type!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"transaction_ids={_transaction_ids!s}, "
            f"ledger_transaction_id={_ledger_transaction_id!s}, "
            f"current_return={_current_return!s}, "
            f"transaction_monitoring_enabled={_transaction_monitoring_enabled!s}, "
            f"compliance_rule_metadata={_compliance_rule_metadata!s}, "
            f"reference_numbers={_reference_numbers!s}, "
            f"vendor_failure_reason={_vendor_failure_reason!s}, "
            f"decision_id={_decision_id!s}, "
            f")"
        )
