"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentMethod1Enum(object):
    """Implementation of the 'PaymentMethod1' enum.

    The method by which the invoice can be paid. `ui` will show the embedded payment
    collection flow. `automatic` will automatically initiate payment based upon the
    account details of the receiving_account id.\nIf the invoice amount is positive,
    the automatically initiated payment order's direction will be debit. If the
    invoice amount is negative, the automatically initiated payment order's direction
    will be credit. One of `manual`, `ui`, or `automatic`.

    Attributes:
        UI: The enum member of type str.
        MANUAL: The enum member of type str.
        AUTOMATIC: The enum member of type str.

    """

    UI = "ui"

    MANUAL = "manual"

    AUTOMATIC = "automatic"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
