"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ReferenceNumberType1Enum(object):
    """Implementation of the 'ReferenceNumberType1' enum.

    The type of reference number.

    Attributes:
        ACH_ORIGINAL_TRACE_NUMBER: The enum member of type str.
        ACH_TRACE_NUMBER: The enum member of type str.
        BANKPROV_PAYMENT_ACTIVITY_DATE: The enum member of type str.
        BANKPROV_PAYMENT_ID: The enum member of type str.
        BNK_DEV_PRENOTIFICATION_ID: The enum member of type str.
        BNK_DEV_TRANSFER_ID: The enum member of type str.
        BOFA_END_TO_END_ID: The enum member of type str.
        BOFA_TRANSACTION_ID: The enum member of type str.
        CHECK_NUMBER: The enum member of type str.
        COLUMN_FX_QUOTE_ID: The enum member of type str.
        COLUMN_REVERSAL_PAIR_TRANSFER_ID: The enum member of type str.
        COLUMN_TRANSFER_ID: The enum member of type str.
        CROSS_RIVER_PAYMENT_ID: The enum member of type str.
        CROSS_RIVER_TRANSACTION_ID: The enum member of type str.
        CURRENCYCLOUD_CONVERSION_ID: The enum member of type str.
        CURRENCYCLOUD_PAYMENT_ID: The enum member of type str.
        DC_BANK_TRANSACTION_ID: The enum member of type str.
        DWOLLA_TRANSACTION_ID: The enum member of type str.
        EFT_TRACE_NUMBER: The enum member of type str.
        EVOLVE_TRANSACTION_ID: The enum member of type str.
        FEDWIRE_IMAD: The enum member of type str.
        FEDWIRE_OMAD: The enum member of type str.
        FIRST_REPUBLIC_INTERNAL_ID: The enum member of type str.
        GOLDMAN_SACHS_COLLECTION_REQUEST_ID: The enum member of type str.
        GOLDMAN_SACHS_END_TO_END_ID: The enum member of type str.
        GOLDMAN_SACHS_PAYMENT_REQUEST_ID: The enum member of type str.
        GOLDMAN_SACHS_REQUEST_ID: The enum member of type str.
        GOLDMAN_SACHS_UNIQUE_PAYMENT_ID: The enum member of type str.
        INTERAC_MESSAGE_ID: The enum member of type str.
        JPMC_CCN: The enum member of type str.
        JPMC_CUSTOMER_REFERENCE_ID: The enum member of type str.
        JPMC_END_TO_END_ID: The enum member of type str.
        JPMC_FIRM_ROOT_ID: The enum member of type str.
        JPMC_P3_ID: The enum member of type str.
        JPMC_PAYMENT_BATCH_ID: The enum member of type str.
        JPMC_PAYMENT_INFORMATION_ID: The enum member of type str.
        JPMC_PAYMENT_RETURNED_DATETIME: The enum member of type str.
        LOB_CHECK_ID: The enum member of type str.
        OTHER: The enum member of type str.
        PARTIAL_SWIFT_MIR: The enum member of type str.
        PNC_CLEARING_REFERENCE: The enum member of type str.
        PNC_INSTRUCTION_ID: The enum member of type str.
        PNC_MULTIPAYMENT_ID: The enum member of type str.
        PNC_PAYMENT_TRACE_ID: The enum member of type str.
        RSPEC_VENDOR_PAYMENT_ID: The enum member of type str.
        RTP_INSTRUCTION_ID: The enum member of type str.
        SIGNET_API_REFERENCE_ID: The enum member of type str.
        SIGNET_CONFIRMATION_ID: The enum member of type str.
        SIGNET_REQUEST_ID: The enum member of type str.
        SILVERGATE_PAYMENT_ID: The enum member of type str.
        SWIFT_MIR: The enum member of type str.
        SWIFT_UETR: The enum member of type str.
        USBANK_PAYMENT_ID: The enum member of type str.
        WELLS_FARGO_PAYMENT_ID: The enum member of type str.
        WELLS_FARGO_TRACE_NUMBER: The enum member of type str.

    """

    ACH_ORIGINAL_TRACE_NUMBER = "ach_original_trace_number"

    ACH_TRACE_NUMBER = "ach_trace_number"

    BANKPROV_PAYMENT_ACTIVITY_DATE = "bankprov_payment_activity_date"

    BANKPROV_PAYMENT_ID = "bankprov_payment_id"

    BNK_DEV_PRENOTIFICATION_ID = "bnk_dev_prenotification_id"

    BNK_DEV_TRANSFER_ID = "bnk_dev_transfer_id"

    BOFA_END_TO_END_ID = "bofa_end_to_end_id"

    BOFA_TRANSACTION_ID = "bofa_transaction_id"

    CHECK_NUMBER = "check_number"

    COLUMN_FX_QUOTE_ID = "column_fx_quote_id"

    COLUMN_REVERSAL_PAIR_TRANSFER_ID = "column_reversal_pair_transfer_id"

    COLUMN_TRANSFER_ID = "column_transfer_id"

    CROSS_RIVER_PAYMENT_ID = "cross_river_payment_id"

    CROSS_RIVER_TRANSACTION_ID = "cross_river_transaction_id"

    CURRENCYCLOUD_CONVERSION_ID = "currencycloud_conversion_id"

    CURRENCYCLOUD_PAYMENT_ID = "currencycloud_payment_id"

    DC_BANK_TRANSACTION_ID = "dc_bank_transaction_id"

    DWOLLA_TRANSACTION_ID = "dwolla_transaction_id"

    EFT_TRACE_NUMBER = "eft_trace_number"

    EVOLVE_TRANSACTION_ID = "evolve_transaction_id"

    FEDWIRE_IMAD = "fedwire_imad"

    FEDWIRE_OMAD = "fedwire_omad"

    FIRST_REPUBLIC_INTERNAL_ID = "first_republic_internal_id"

    GOLDMAN_SACHS_COLLECTION_REQUEST_ID = "goldman_sachs_collection_request_id"

    GOLDMAN_SACHS_END_TO_END_ID = "goldman_sachs_end_to_end_id"

    GOLDMAN_SACHS_PAYMENT_REQUEST_ID = "goldman_sachs_payment_request_id"

    GOLDMAN_SACHS_REQUEST_ID = "goldman_sachs_request_id"

    GOLDMAN_SACHS_UNIQUE_PAYMENT_ID = "goldman_sachs_unique_payment_id"

    INTERAC_MESSAGE_ID = "interac_message_id"

    JPMC_CCN = "jpmc_ccn"

    JPMC_CUSTOMER_REFERENCE_ID = "jpmc_customer_reference_id"

    JPMC_END_TO_END_ID = "jpmc_end_to_end_id"

    JPMC_FIRM_ROOT_ID = "jpmc_firm_root_id"

    JPMC_P3_ID = "jpmc_p3_id"

    JPMC_PAYMENT_BATCH_ID = "jpmc_payment_batch_id"

    JPMC_PAYMENT_INFORMATION_ID = "jpmc_payment_information_id"

    JPMC_PAYMENT_RETURNED_DATETIME = "jpmc_payment_returned_datetime"

    LOB_CHECK_ID = "lob_check_id"

    OTHER = "other"

    PARTIAL_SWIFT_MIR = "partial_swift_mir"

    PNC_CLEARING_REFERENCE = "pnc_clearing_reference"

    PNC_INSTRUCTION_ID = "pnc_instruction_id"

    PNC_MULTIPAYMENT_ID = "pnc_multipayment_id"

    PNC_PAYMENT_TRACE_ID = "pnc_payment_trace_id"

    RSPEC_VENDOR_PAYMENT_ID = "rspec_vendor_payment_id"

    RTP_INSTRUCTION_ID = "rtp_instruction_id"

    SIGNET_API_REFERENCE_ID = "signet_api_reference_id"

    SIGNET_CONFIRMATION_ID = "signet_confirmation_id"

    SIGNET_REQUEST_ID = "signet_request_id"

    SILVERGATE_PAYMENT_ID = "silvergate_payment_id"

    SWIFT_MIR = "swift_mir"

    SWIFT_UETR = "swift_uetr"

    USBANK_PAYMENT_ID = "usbank_payment_id"

    WELLS_FARGO_PAYMENT_ID = "wells_fargo_payment_id"

    WELLS_FARGO_TRACE_NUMBER = "wells_fargo_trace_number"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
