"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.ledger_transaction_create_request import (
    LedgerTransactionCreateRequest,
)


class ReversalCreateRequest(object):
    """Implementation of the 'reversal_create_request' model.

    Attributes:
        reason (Reason1): The reason for the reversal. Must be one of `duplicate`,
            `incorrect_amount`, `incorrect_receiving_account`,
            `date_earlier_than_intended`, `date_later_than_intended`.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        ledger_transaction (LedgerTransactionCreateRequest): The model property of
            type LedgerTransactionCreateRequest.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "reason": "reason",
        "metadata": "metadata",
        "ledger_transaction": "ledger_transaction",
    }

    _optionals = [
        "metadata",
        "ledger_transaction",
    ]

    def __init__(
        self,
        reason=None,
        metadata=APIHelper.SKIP,
        ledger_transaction=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ReversalCreateRequest instance."""
        # Initialize members of the class
        self.reason = reason
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if ledger_transaction is not APIHelper.SKIP:
            self.ledger_transaction = ledger_transaction

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        reason =\
            dictionary.get("reason")\
            if dictionary.get("reason")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        ledger_transaction =\
            LedgerTransactionCreateRequest.from_dictionary(
                dictionary.get("ledger_transaction"))\
                if "ledger_transaction" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(reason,
                   metadata,
                   ledger_transaction,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _reason=self.reason
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _ledger_transaction=(
            self.ledger_transaction
            if hasattr(self, "ledger_transaction")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reason={_reason!r}, "
            f"metadata={_metadata!r}, "
            f"ledger_transaction={_ledger_transaction!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _reason=self.reason
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _ledger_transaction=(
            self.ledger_transaction
            if hasattr(self, "ledger_transaction")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reason={_reason!s}, "
            f"metadata={_metadata!s}, "
            f"ledger_transaction={_ledger_transaction!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
