"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper


class RoutingDetailCreateRequest(object):
    """Implementation of the 'routing_detail_create_request' model.

    Attributes:
        routing_number (str): The routing number of the bank.
        routing_number_type (RoutingNumberTypeEnum): One of `aba`, `swift`, `ca_cpa`,
            `au_bsb`, `gb_sort_code`, `in_ifsc`, `cnaps`.
        payment_type (PaymentType1Enum): If the routing detail is to be used for a
            specific payment type this field will be populated, otherwise null.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "routing_number": "routing_number",
        "routing_number_type": "routing_number_type",
        "payment_type": "payment_type",
    }

    _optionals = [
        "payment_type",
    ]

    _nullables = [
        "payment_type",
    ]

    def __init__(
        self,
        routing_number=None,
        routing_number_type=None,
        payment_type=APIHelper.SKIP):
        """Initialize a RoutingDetailCreateRequest instance."""
        # Initialize members of the class
        self.routing_number = routing_number
        self.routing_number_type = routing_number_type
        if payment_type is not APIHelper.SKIP:
            self.payment_type = payment_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        routing_number =\
            dictionary.get("routing_number")\
            if dictionary.get("routing_number")\
                else None
        routing_number_type =\
            dictionary.get("routing_number_type")\
            if dictionary.get("routing_number_type")\
                else None
        payment_type =\
            dictionary.get("payment_type")\
            if "payment_type" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(routing_number,
                   routing_number_type,
                   payment_type)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _routing_number=self.routing_number
        _routing_number_type=self.routing_number_type
        _payment_type=(
            self.payment_type
            if hasattr(self, "payment_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"routing_number={_routing_number!r}, "
            f"routing_number_type={_routing_number_type!r}, "
            f"payment_type={_payment_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _routing_number=self.routing_number
        _routing_number_type=self.routing_number_type
        _payment_type=(
            self.payment_type
            if hasattr(self, "payment_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"routing_number={_routing_number!s}, "
            f"routing_number_type={_routing_number_type!s}, "
            f"payment_type={_payment_type!s}, "
            f")"
        )
