"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Status24(object):
    """Implementation of the 'status24' enum.

    Attributes:
        APPROVED: The enum member of type str.
        CANCELLED: The enum member of type str.
        COMPLETED: The enum member of type str.
        DENIED: The enum member of type str.
        FAILED: The enum member of type str.
        NEEDS_APPROVAL: The enum member of type str.
        PENDING: The enum member of type str.
        PROCESSING: The enum member of type str.
        RETURNED: The enum member of type str.
        REVERSED: The enum member of type str.
        SENT: The enum member of type str.

    """

    APPROVED = "approved"

    CANCELLED = "cancelled"

    COMPLETED = "completed"

    DENIED = "denied"

    FAILED = "failed"

    NEEDS_APPROVAL = "needs_approval"

    PENDING = "pending"

    PROCESSING = "processing"

    RETURNED = "returned"

    REVERSED = "reversed"

    SENT = "sent"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
