"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Status11Enum(object):
    """Implementation of the 'Status11' enum.

    To post a ledger transaction at creation, use `posted`.

    Attributes:
        ARCHIVED: The enum member of type str.
        PENDING: The enum member of type str.
        POSTED: The enum member of type str.

    """

    ARCHIVED = "archived"

    PENDING = "pending"

    POSTED = "posted"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
