"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class SubtypeEnum(object):
    """Implementation of the 'Subtype' enum.

    An additional layer of classification for the type of payment order you are
    doing. This field is only used for `ach` payment orders currently. For `ach`
    payment orders, the `subtype`  represents the SEC code. We currently support
    `CCD`, `PPD`, `IAT`, `CTX`, `WEB`, `CIE`, and `TEL`.

    Attributes:
        ENUM_0C: The enum member of type str.
        ENUM_0N: The enum member of type str.
        ENUM_0S: The enum member of type str.
        CCD: The enum member of type str.
        CIE: The enum member of type str.
        CTX: The enum member of type str.
        IAT: The enum member of type str.
        PPD: The enum member of type str.
        TEL: The enum member of type str.
        WEB: The enum member of type str.

    """

    _all_values = ["0C", "0N", "0S", "CCD", "CIE", "CTX", "IAT", "PPD", "TEL",
        "WEB"]
    ENUM_0C = "0C"

    ENUM_0N = "0N"

    ENUM_0S = "0S"

    CCD = "CCD"

    CIE = "CIE"

    CTX = "CTX"

    IAT = "IAT"

    PPD = "PPD"

    TEL = "TEL"

    WEB = "WEB"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
