"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from moderntreasury.api_helper import APIHelper


class Transaction(object):
    """Implementation of the 'transaction' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        amount (int): Value in specified currency's smallest unit. e.g. $10 would be
            represented as 1000.
        currency (Currency): Three-letter ISO currency code.
        direction (str): Either `credit` or `debit`.
        vendor_description (str): The transaction detail text that often appears in
            on your bank statement and in your banking portal.
        vendor_code (str): When applicable, the bank-given code that determines the
            transaction's category. For most banks this is the BAI2/BTRS transaction
            code.
        vendor_code_type (VendorCodeType1): The type of `vendor_code` being reported.
            Can be one of `bai2`, `bankprov`, `bnk_dev`, `cleartouch`,
            `currencycloud`, `cross_river`, `dc_bank`, `dwolla`, `evolve`,
            `goldman_sachs`, `iso20022`, `jpmc`, `mx`, `signet`, `silvergate`,
            `swift`, or `us_bank`.
        vendor_id (str): An identifier given to this transaction by the bank.
        as_of_date (date): The date on which the transaction occurred.
        as_of_time (datetime): The time on which the transaction occurred. Depending
            on the granularity of the timestamp information received from the bank,
            it may be `null`.
        internal_account_id (uuid|str): The ID of the relevant Internal Account.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        posted (bool): This field will be `true` if the transaction has posted to the
            account.
        vendor_customer_id (str): An identifier given to this transaction by the
            bank, often `null`.
        reconciled (bool): This field will be `true` if a transaction is reconciled
            by the Modern Treasury system. This means that it has transaction line
            items that sum up to the transaction's amount.
        details (Dict[str, str]): This field contains additional information that the
            bank provided about the transaction. This is structured data. Some of the
            data in here might overlap with what is in the `vendor_description`. For
            example, the OBI could be a part of the vendor description, and it would
            also be included in here. The attributes that are passed through the
            details field will vary based on your banking partner. Currently, the
            following keys may be in the details object: `originator_name`,
            `originator_to_beneficiary_information`.
        mtype (Type11): The type of the transaction. Can be one of `ach`, `wire`,
            `check`, `rtp`, `book`, or `sen`.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "amount": "amount",
        "currency": "currency",
        "direction": "direction",
        "vendor_description": "vendor_description",
        "vendor_code": "vendor_code",
        "vendor_code_type": "vendor_code_type",
        "vendor_id": "vendor_id",
        "as_of_date": "as_of_date",
        "as_of_time": "as_of_time",
        "internal_account_id": "internal_account_id",
        "metadata": "metadata",
        "posted": "posted",
        "vendor_customer_id": "vendor_customer_id",
        "reconciled": "reconciled",
        "details": "details",
        "mtype": "type",
    }

    _nullables = [
        "discarded_at",
        "vendor_description",
        "vendor_code",
        "vendor_code_type",
        "vendor_id",
        "as_of_date",
        "as_of_time",
        "vendor_customer_id",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        amount=None,
        currency=None,
        direction=None,
        vendor_description=None,
        vendor_code=None,
        vendor_code_type=None,
        vendor_id=None,
        as_of_date=None,
        as_of_time=None,
        internal_account_id=None,
        metadata=None,
        posted=None,
        vendor_customer_id=None,
        reconciled=None,
        details=None,
        mtype=None):
        """Initialize a Transaction instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.amount = amount
        self.currency = currency
        self.direction = direction
        self.vendor_description = vendor_description
        self.vendor_code = vendor_code
        self.vendor_code_type = vendor_code_type
        self.vendor_id = vendor_id
        self.as_of_date = as_of_date
        self.as_of_time =\
             APIHelper.apply_datetime_converter(
            as_of_time, APIHelper.RFC3339DateTime)\
             if as_of_time else None
        self.internal_account_id = internal_account_id
        self.metadata = metadata
        self.posted = posted
        self.vendor_customer_id = vendor_customer_id
        self.reconciled = reconciled
        self.details = details
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else None
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        vendor_description =\
            dictionary.get("vendor_description")\
            if dictionary.get("vendor_description")\
                else None
        vendor_code =\
            dictionary.get("vendor_code")\
            if dictionary.get("vendor_code")\
                else None
        vendor_code_type =\
            dictionary.get("vendor_code_type")\
            if dictionary.get("vendor_code_type")\
                else None
        vendor_id =\
            dictionary.get("vendor_id")\
            if dictionary.get("vendor_id")\
                else None
        as_of_date = dateutil.parser.parse(
            dictionary.get("as_of_date")).date()\
            if dictionary.get("as_of_date") else None
        as_of_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("as_of_time")).datetime\
            if dictionary.get("as_of_time") else None
        internal_account_id =\
            dictionary.get("internal_account_id")\
            if dictionary.get("internal_account_id")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None
        posted =\
            dictionary.get("posted")\
            if "posted" in dictionary.keys()\
                else None
        vendor_customer_id =\
            dictionary.get("vendor_customer_id")\
            if dictionary.get("vendor_customer_id")\
                else None
        reconciled =\
            dictionary.get("reconciled")\
            if "reconciled" in dictionary.keys()\
                else None
        details =\
            dictionary.get("details")\
            if dictionary.get("details")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   amount,
                   currency,
                   direction,
                   vendor_description,
                   vendor_code,
                   vendor_code_type,
                   vendor_id,
                   as_of_date,
                   as_of_time,
                   internal_account_id,
                   metadata,
                   posted,
                   vendor_customer_id,
                   reconciled,
                   details,
                   mtype)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _amount=self.amount
        _currency=self.currency
        _direction=self.direction
        _vendor_description=self.vendor_description
        _vendor_code=self.vendor_code
        _vendor_code_type=self.vendor_code_type
        _vendor_id=self.vendor_id
        _as_of_date=self.as_of_date
        _as_of_time=self.as_of_time
        _internal_account_id=self.internal_account_id
        _metadata=self.metadata
        _posted=self.posted
        _vendor_customer_id=self.vendor_customer_id
        _reconciled=self.reconciled
        _details=self.details
        _mtype=self.mtype
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"direction={_direction!r}, "
            f"vendor_description={_vendor_description!r}, "
            f"vendor_code={_vendor_code!r}, "
            f"vendor_code_type={_vendor_code_type!r}, "
            f"vendor_id={_vendor_id!r}, "
            f"as_of_date={_as_of_date!r}, "
            f"as_of_time={_as_of_time!r}, "
            f"internal_account_id={_internal_account_id!r}, "
            f"metadata={_metadata!r}, "
            f"posted={_posted!r}, "
            f"vendor_customer_id={_vendor_customer_id!r}, "
            f"reconciled={_reconciled!r}, "
            f"details={_details!r}, "
            f"mtype={_mtype!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _amount=self.amount
        _currency=self.currency
        _direction=self.direction
        _vendor_description=self.vendor_description
        _vendor_code=self.vendor_code
        _vendor_code_type=self.vendor_code_type
        _vendor_id=self.vendor_id
        _as_of_date=self.as_of_date
        _as_of_time=self.as_of_time
        _internal_account_id=self.internal_account_id
        _metadata=self.metadata
        _posted=self.posted
        _vendor_customer_id=self.vendor_customer_id
        _reconciled=self.reconciled
        _details=self.details
        _mtype=self.mtype
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"direction={_direction!s}, "
            f"vendor_description={_vendor_description!s}, "
            f"vendor_code={_vendor_code!s}, "
            f"vendor_code_type={_vendor_code_type!s}, "
            f"vendor_id={_vendor_id!s}, "
            f"as_of_date={_as_of_date!s}, "
            f"as_of_time={_as_of_time!s}, "
            f"internal_account_id={_internal_account_id!s}, "
            f"metadata={_metadata!s}, "
            f"posted={_posted!s}, "
            f"vendor_customer_id={_vendor_customer_id!s}, "
            f"reconciled={_reconciled!s}, "
            f"details={_details!s}, "
            f"mtype={_mtype!s}, "
            f")"
        )
