"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class VendorCodeTypeEnum(object):
    """Implementation of the 'VendorCodeType' enum.

    The code used by the bank when reporting this specific balance.

    Attributes:
        BAI2: The enum member of type str.
        BANKPROV: The enum member of type str.
        BNK_DEV: The enum member of type str.
        CLEARTOUCH: The enum member of type str.
        COLUMN: The enum member of type str.
        CROSS_RIVER: The enum member of type str.
        CURRENCYCLOUD: The enum member of type str.
        DC_BANK: The enum member of type str.
        DWOLLA: The enum member of type str.
        EVOLVE: The enum member of type str.
        GOLDMAN_SACHS: The enum member of type str.
        ISO20022: The enum member of type str.
        JPMC: The enum member of type str.
        MX: The enum member of type str.
        PLAID: The enum member of type str.
        RSPEC_VENDOR: The enum member of type str.
        SIGNET: The enum member of type str.
        SILVERGATE: The enum member of type str.
        SWIFT: The enum member of type str.
        US_BANK: The enum member of type str.

    """

    BAI2 = "bai2"

    BANKPROV = "bankprov"

    BNK_DEV = "bnk_dev"

    CLEARTOUCH = "cleartouch"

    COLUMN = "column"

    CROSS_RIVER = "cross_river"

    CURRENCYCLOUD = "currencycloud"

    DC_BANK = "dc_bank"

    DWOLLA = "dwolla"

    EVOLVE = "evolve"

    GOLDMAN_SACHS = "goldman_sachs"

    ISO20022 = "iso20022"

    JPMC = "jpmc"

    MX = "mx"

    PLAID = "plaid"

    RSPEC_VENDOR = "rspec_vendor"

    SIGNET = "signet"

    SILVERGATE = "silvergate"

    SWIFT = "swift"

    US_BANK = "us_bank"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
