"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.account_detail_create_request import (
    AccountDetailCreateRequest,
)
from moderntreasury.models.routing_detail_create_request import (
    RoutingDetailCreateRequest,
)


class VirtualAccountCreateRequest(object):
    """Implementation of the 'virtual_account_create_request' model.

    Attributes:
        name (str): The name of the virtual account.
        description (str): An optional description for internal use.
        counterparty_id (uuid|str): The ID of the counterparty that the virtual
            account belongs to.
        internal_account_id (uuid|str): The ID of the internal account that this
            virtual account is associated with.
        account_details (List[AccountDetailCreateRequest]): An array of account
            detail objects.
        routing_details (List[RoutingDetailCreateRequest]): An array of routing
            detail objects.
        debit_ledger_account_id (uuid|str): The ID of a debit normal ledger account.
            When money enters the virtual account, this ledger account will be
            debited. Must be accompanied by a credit_ledger_account_id if present.
        credit_ledger_account_id (uuid|str): The ID of a credit normal ledger
            account. When money leaves the virtual account, this ledger account will
            be credited. Must be accompanied by a debit_ledger_account_id if present.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "internal_account_id": "internal_account_id",
        "description": "description",
        "counterparty_id": "counterparty_id",
        "account_details": "account_details",
        "routing_details": "routing_details",
        "debit_ledger_account_id": "debit_ledger_account_id",
        "credit_ledger_account_id": "credit_ledger_account_id",
        "metadata": "metadata",
    }

    _optionals = [
        "description",
        "counterparty_id",
        "account_details",
        "routing_details",
        "debit_ledger_account_id",
        "credit_ledger_account_id",
        "metadata",
    ]

    def __init__(
        self,
        name=None,
        internal_account_id=None,
        description=APIHelper.SKIP,
        counterparty_id=APIHelper.SKIP,
        account_details=APIHelper.SKIP,
        routing_details=APIHelper.SKIP,
        debit_ledger_account_id=APIHelper.SKIP,
        credit_ledger_account_id=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a VirtualAccountCreateRequest instance."""
        # Initialize members of the class
        self.name = name
        if description is not APIHelper.SKIP:
            self.description = description
        if counterparty_id is not APIHelper.SKIP:
            self.counterparty_id = counterparty_id
        self.internal_account_id = internal_account_id
        if account_details is not APIHelper.SKIP:
            self.account_details = account_details
        if routing_details is not APIHelper.SKIP:
            self.routing_details = routing_details
        if debit_ledger_account_id is not APIHelper.SKIP:
            self.debit_ledger_account_id = debit_ledger_account_id
        if credit_ledger_account_id is not APIHelper.SKIP:
            self.credit_ledger_account_id = credit_ledger_account_id
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        internal_account_id =\
            dictionary.get("internal_account_id")\
            if dictionary.get("internal_account_id")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if dictionary.get("counterparty_id")\
                else APIHelper.SKIP
        account_details = None
        if dictionary.get("account_details") is not None:
            account_details = [
                AccountDetailCreateRequest.from_dictionary(x)
                    for x in dictionary.get("account_details")
            ]
        else:
            account_details = APIHelper.SKIP
        routing_details = None
        if dictionary.get("routing_details") is not None:
            routing_details = [
                RoutingDetailCreateRequest.from_dictionary(x)
                    for x in dictionary.get("routing_details")
            ]
        else:
            routing_details = APIHelper.SKIP
        debit_ledger_account_id =\
            dictionary.get("debit_ledger_account_id")\
            if dictionary.get("debit_ledger_account_id")\
                else APIHelper.SKIP
        credit_ledger_account_id =\
            dictionary.get("credit_ledger_account_id")\
            if dictionary.get("credit_ledger_account_id")\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   internal_account_id,
                   description,
                   counterparty_id,
                   account_details,
                   routing_details,
                   debit_ledger_account_id,
                   credit_ledger_account_id,
                   metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _internal_account_id=self.internal_account_id
        _account_details=(
            self.account_details
            if hasattr(self, "account_details")
            else None
        )
        _routing_details=(
            self.routing_details
            if hasattr(self, "routing_details")
            else None
        )
        _debit_ledger_account_id=(
            self.debit_ledger_account_id
            if hasattr(self, "debit_ledger_account_id")
            else None
        )
        _credit_ledger_account_id=(
            self.credit_ledger_account_id
            if hasattr(self, "credit_ledger_account_id")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"internal_account_id={_internal_account_id!r}, "
            f"account_details={_account_details!r}, "
            f"routing_details={_routing_details!r}, "
            f"debit_ledger_account_id={_debit_ledger_account_id!r}, "
            f"credit_ledger_account_id={_credit_ledger_account_id!r}, "
            f"metadata={_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _counterparty_id=(
            self.counterparty_id
            if hasattr(self, "counterparty_id")
            else None
        )
        _internal_account_id=self.internal_account_id
        _account_details=(
            self.account_details
            if hasattr(self, "account_details")
            else None
        )
        _routing_details=(
            self.routing_details
            if hasattr(self, "routing_details")
            else None
        )
        _debit_ledger_account_id=(
            self.debit_ledger_account_id
            if hasattr(self, "debit_ledger_account_id")
            else None
        )
        _credit_ledger_account_id=(
            self.credit_ledger_account_id
            if hasattr(self, "credit_ledger_account_id")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"internal_account_id={_internal_account_id!s}, "
            f"account_details={_account_details!s}, "
            f"routing_details={_routing_details!s}, "
            f"debit_ledger_account_id={_debit_ledger_account_id!s}, "
            f"credit_ledger_account_id={_credit_ledger_account_id!s}, "
            f"metadata={_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
