"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from moderntreasury.api_helper import APIHelper
from moderntreasury.models.account_detail import (
    AccountDetail,
)
from moderntreasury.models.routing_detail import (
    RoutingDetail,
)


class VirtualAccount(object):
    """Implementation of the 'virtual_account' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        object (str): The model property of type str.
        live_mode (bool): This field will be true if this object exists in the live
            environment or false if it exists in the test environment.
        created_at (datetime): The model property of type datetime.
        updated_at (datetime): The model property of type datetime.
        discarded_at (datetime): The model property of type datetime.
        name (str): The name of the virtual account.
        description (str): An optional free-form description for internal use.
        counterparty_id (uuid|str): The ID of a counterparty that the virtual account
            belongs to. Optional.
        internal_account_id (uuid|str): The ID of the internal account that the
            virtual account is in.
        account_details (List[AccountDetail]): An array of account detail objects.
        routing_details (List[RoutingDetail]): An array of routing detail objects.
            These will be the routing details of the internal account.
        debit_ledger_account_id (uuid|str): The ID of a debit normal ledger account.
            When money enters the virtual account, this ledger account will be
            debited. Must be accompanied by a credit_ledger_account_id if present.
        credit_ledger_account_id (uuid|str): The ID of a credit normal ledger
            account. When money enters the virtual account, this ledger account will
            be credited. Must be accompanied by a debit_ledger_account_id if present.
        metadata (Dict[str, str]): Additional data represented as key-value pairs.
            Both the key and value must be strings.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "object": "object",
        "live_mode": "live_mode",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "discarded_at": "discarded_at",
        "name": "name",
        "description": "description",
        "counterparty_id": "counterparty_id",
        "internal_account_id": "internal_account_id",
        "account_details": "account_details",
        "routing_details": "routing_details",
        "debit_ledger_account_id": "debit_ledger_account_id",
        "credit_ledger_account_id": "credit_ledger_account_id",
        "metadata": "metadata",
    }

    _nullables = [
        "discarded_at",
        "description",
        "counterparty_id",
        "debit_ledger_account_id",
        "credit_ledger_account_id",
    ]

    def __init__(
        self,
        id=None,
        object=None,
        live_mode=None,
        created_at=None,
        updated_at=None,
        discarded_at=None,
        name=None,
        description=None,
        counterparty_id=None,
        internal_account_id=None,
        account_details=None,
        routing_details=None,
        debit_ledger_account_id=None,
        credit_ledger_account_id=None,
        metadata=None):
        """Initialize a VirtualAccount instance."""
        # Initialize members of the class
        self.id = id
        self.object = object
        self.live_mode = live_mode
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.discarded_at =\
             APIHelper.apply_datetime_converter(
            discarded_at, APIHelper.RFC3339DateTime)\
             if discarded_at else None
        self.name = name
        self.description = description
        self.counterparty_id = counterparty_id
        self.internal_account_id = internal_account_id
        self.account_details = account_details
        self.routing_details = routing_details
        self.debit_ledger_account_id = debit_ledger_account_id
        self.credit_ledger_account_id = credit_ledger_account_id
        self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        live_mode =\
            dictionary.get("live_mode")\
            if "live_mode" in dictionary.keys()\
                else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else None
        discarded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("discarded_at")).datetime\
            if dictionary.get("discarded_at") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        counterparty_id =\
            dictionary.get("counterparty_id")\
            if dictionary.get("counterparty_id")\
                else None
        internal_account_id =\
            dictionary.get("internal_account_id")\
            if dictionary.get("internal_account_id")\
                else None
        account_details = None
        if dictionary.get("account_details") is not None:
            account_details = [
                AccountDetail.from_dictionary(x)
                    for x in dictionary.get("account_details")
            ]
        routing_details = None
        if dictionary.get("routing_details") is not None:
            routing_details = [
                RoutingDetail.from_dictionary(x)
                    for x in dictionary.get("routing_details")
            ]
        debit_ledger_account_id =\
            dictionary.get("debit_ledger_account_id")\
            if dictionary.get("debit_ledger_account_id")\
                else None
        credit_ledger_account_id =\
            dictionary.get("credit_ledger_account_id")\
            if dictionary.get("credit_ledger_account_id")\
                else None
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else None

        # Return an object of this model
        return cls(id,
                   object,
                   live_mode,
                   created_at,
                   updated_at,
                   discarded_at,
                   name,
                   description,
                   counterparty_id,
                   internal_account_id,
                   account_details,
                   routing_details,
                   debit_ledger_account_id,
                   credit_ledger_account_id,
                   metadata)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _counterparty_id=self.counterparty_id
        _internal_account_id=self.internal_account_id
        _account_details=self.account_details
        _routing_details=self.routing_details
        _debit_ledger_account_id=self.debit_ledger_account_id
        _credit_ledger_account_id=self.credit_ledger_account_id
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"live_mode={_live_mode!r}, "
            f"created_at={_created_at!r}, "
            f"updated_at={_updated_at!r}, "
            f"discarded_at={_discarded_at!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"counterparty_id={_counterparty_id!r}, "
            f"internal_account_id={_internal_account_id!r}, "
            f"account_details={_account_details!r}, "
            f"routing_details={_routing_details!r}, "
            f"debit_ledger_account_id={_debit_ledger_account_id!r}, "
            f"credit_ledger_account_id={_credit_ledger_account_id!r}, "
            f"metadata={_metadata!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _object=self.object
        _live_mode=self.live_mode
        _created_at=self.created_at
        _updated_at=self.updated_at
        _discarded_at=self.discarded_at
        _name=self.name
        _description=self.description
        _counterparty_id=self.counterparty_id
        _internal_account_id=self.internal_account_id
        _account_details=self.account_details
        _routing_details=self.routing_details
        _debit_ledger_account_id=self.debit_ledger_account_id
        _credit_ledger_account_id=self.credit_ledger_account_id
        _metadata=self.metadata
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"live_mode={_live_mode!s}, "
            f"created_at={_created_at!s}, "
            f"updated_at={_updated_at!s}, "
            f"discarded_at={_discarded_at!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"counterparty_id={_counterparty_id!s}, "
            f"internal_account_id={_internal_account_id!s}, "
            f"account_details={_account_details!s}, "
            f"routing_details={_routing_details!s}, "
            f"debit_ledger_account_id={_debit_ledger_account_id!s}, "
            f"credit_ledger_account_id={_credit_ledger_account_id!s}, "
            f"metadata={_metadata!s}, "
            f")"
        )
