"""moderntreasury.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from moderntreasury.configuration import (
    Configuration,
    Environment,
)
from moderntreasury.controllers.account_collection_flow_controller import (
    AccountCollectionFlowController,
)
from moderntreasury.controllers.account_detail_controller import (
    AccountDetailController,
)
from moderntreasury.controllers.balance_report_controller import (
    BalanceReportController,
)
from moderntreasury.controllers.base_controller import (
    BaseController,
)
from moderntreasury.controllers.connection_controller import (
    ConnectionController,
)
from moderntreasury.controllers.counterparty_controller import (
    CounterpartyController,
)
from moderntreasury.controllers.document_controller import (
    DocumentController,
)
from moderntreasury.controllers.event_controller import (
    EventController,
)
from moderntreasury.controllers.expected_payment_controller import (
    ExpectedPaymentController,
)
from moderntreasury.controllers.external_account_controller import (
    ExternalAccountController,
)
from moderntreasury.controllers.incoming_payment_detail_controller import (
    IncomingPaymentDetailController,
)
from moderntreasury.controllers.internal_account_controller import (
    InternalAccountController,
)
from moderntreasury.controllers.invoice_controller import (
    InvoiceController,
)
from moderntreasury.controllers.invoice_line_item_controller import (
    InvoiceLineItemController,
)
from moderntreasury.controllers.ledger_account_category_controller import (
    LedgerAccountCategoryController,
)
from moderntreasury.controllers.ledger_account_controller import (
    LedgerAccountController,
)
from moderntreasury.controllers.ledger_account_payout_controller import (
    LedgerAccountPayoutController,
)
from moderntreasury.controllers.ledger_account_statement_controller import (
    LedgerAccountStatementController,
)
from moderntreasury.controllers.ledger_controller import (
    LedgerController,
)
from moderntreasury.controllers.ledger_entry_controller import (
    LedgerEntryController,
)
from moderntreasury.controllers.ledger_event_handler_controller import (
    LedgerEventHandlerController,
)
from moderntreasury.controllers.ledger_transaction_controller import (
    LedgerTransactionController,
)
from moderntreasury.controllers.ledgerable_event_controller import (
    LedgerableEventController,
)
from moderntreasury.controllers.line_item_controller import (
    LineItemController,
)
from moderntreasury.controllers.paper_item_controller import (
    PaperItemController,
)
from moderntreasury.controllers.payment_flow_controller import (
    PaymentFlowController,
)
from moderntreasury.controllers.payment_order_controller import (
    PaymentOrderController,
)
from moderntreasury.controllers.payment_reference_controller import (
    PaymentReferenceController,
)
from moderntreasury.controllers.ping_controller import (
    PingController,
)
from moderntreasury.controllers.return_controller import (
    ReturnController,
)
from moderntreasury.controllers.reversal_controller import (
    ReversalController,
)
from moderntreasury.controllers.routing_detail_controller import (
    RoutingDetailController,
)
from moderntreasury.controllers.transaction_controller import (
    TransactionController,
)
from moderntreasury.controllers.transaction_line_item_controller import (
    TransactionLineItemController,
)
from moderntreasury.controllers.validation_controller import (
    ValidationController,
)
from moderntreasury.controllers.virtual_account_controller import (
    VirtualAccountController,
)
from moderntreasury.http.auth.basic_auth import (
    BasicAuth,
)


class ModerntreasuryClient(object):
    """Client that provide access to the ModerntreasuryClient APIs."""

    @LazyProperty
    def account_detail(self):
        """Provide access to the AccountDetailController endpoints."""
        return AccountDetailController(self.global_configuration)

    @LazyProperty
    def balance_report(self):
        """Provide access to the BalanceReportController endpoints."""
        return BalanceReportController(self.global_configuration)

    @LazyProperty
    def connection(self):
        """Provide access to the ConnectionController endpoints."""
        return ConnectionController(self.global_configuration)

    @LazyProperty
    def counterparty(self):
        """Provide access to the CounterpartyController endpoints."""
        return CounterpartyController(self.global_configuration)

    @LazyProperty
    def document(self):
        """Provide access to the DocumentController endpoints."""
        return DocumentController(self.global_configuration)

    @LazyProperty
    def event(self):
        """Provide access to the EventController endpoints."""
        return EventController(self.global_configuration)

    @LazyProperty
    def expected_payment(self):
        """Provide access to the ExpectedPaymentController endpoints."""
        return ExpectedPaymentController(self.global_configuration)

    @LazyProperty
    def external_account(self):
        """Provide access to the ExternalAccountController endpoints."""
        return ExternalAccountController(self.global_configuration)

    @LazyProperty
    def incoming_payment_detail(self):
        """Provide access to the IncomingPaymentDetailController endpoints."""
        return IncomingPaymentDetailController(self.global_configuration)

    @LazyProperty
    def internal_account(self):
        """Provide access to the InternalAccountController endpoints."""
        return InternalAccountController(self.global_configuration)

    @LazyProperty
    def invoice_line_item(self):
        """Provide access to the InvoiceLineItemController endpoints."""
        return InvoiceLineItemController(self.global_configuration)

    @LazyProperty
    def invoice(self):
        """Provide access to the InvoiceController endpoints."""
        return InvoiceController(self.global_configuration)

    @LazyProperty
    def ledger_account_category(self):
        """Provide access to the LedgerAccountCategoryController endpoints."""
        return LedgerAccountCategoryController(self.global_configuration)

    @LazyProperty
    def ledger_account_payout(self):
        """Provide access to the LedgerAccountPayoutController endpoints."""
        return LedgerAccountPayoutController(self.global_configuration)

    @LazyProperty
    def ledger_account_statement(self):
        """Provide access to the LedgerAccountStatementController endpoints."""
        return LedgerAccountStatementController(self.global_configuration)

    @LazyProperty
    def ledger_account(self):
        """Provide access to the LedgerAccountController endpoints."""
        return LedgerAccountController(self.global_configuration)

    @LazyProperty
    def ledger_entry(self):
        """Provide access to the LedgerEntryController endpoints."""
        return LedgerEntryController(self.global_configuration)

    @LazyProperty
    def ledger_event_handler(self):
        """Provide access to the LedgerEventHandlerController endpoints."""
        return LedgerEventHandlerController(self.global_configuration)

    @LazyProperty
    def ledger_transaction(self):
        """Provide access to the LedgerTransactionController endpoints."""
        return LedgerTransactionController(self.global_configuration)

    @LazyProperty
    def ledgerable_event(self):
        """Provide access to the LedgerableEventController endpoints."""
        return LedgerableEventController(self.global_configuration)

    @LazyProperty
    def ledger(self):
        """Provide access to the LedgerController endpoints."""
        return LedgerController(self.global_configuration)

    @LazyProperty
    def line_item(self):
        """Provide access to the LineItemController endpoints."""
        return LineItemController(self.global_configuration)

    @LazyProperty
    def paper_item(self):
        """Provide access to the PaperItemController endpoints."""
        return PaperItemController(self.global_configuration)

    @LazyProperty
    def payment_order(self):
        """Provide access to the PaymentOrderController endpoints."""
        return PaymentOrderController(self.global_configuration)

    @LazyProperty
    def payment_reference(self):
        """Provide access to the PaymentReferenceController endpoints."""
        return PaymentReferenceController(self.global_configuration)

    @LazyProperty
    def ping(self):
        """Provide access to the PingController endpoints."""
        return PingController(self.global_configuration)

    @LazyProperty
    def mreturn(self):
        """Provide access to the ReturnController endpoints."""
        return ReturnController(self.global_configuration)

    @LazyProperty
    def reversal(self):
        """Provide access to the ReversalController endpoints."""
        return ReversalController(self.global_configuration)

    @LazyProperty
    def routing_detail(self):
        """Provide access to the RoutingDetailController endpoints."""
        return RoutingDetailController(self.global_configuration)

    @LazyProperty
    def transaction_line_item(self):
        """Provide access to the TransactionLineItemController endpoints."""
        return TransactionLineItemController(self.global_configuration)

    @LazyProperty
    def transaction(self):
        """Provide access to the TransactionController endpoints."""
        return TransactionController(self.global_configuration)

    @LazyProperty
    def validation(self):
        """Provide access to the ValidationController endpoints."""
        return ValidationController(self.global_configuration)

    @LazyProperty
    def virtual_account(self):
        """Provide access to the VirtualAccountController endpoints."""
        return VirtualAccountController(self.global_configuration)

    @LazyProperty
    def account_collection_flow(self):
        """Provide access to the AccountCollectionFlowController endpoints."""
        return AccountCollectionFlowController(self.global_configuration)

    @LazyProperty
    def payment_flow(self):
        """Provide access to the PaymentFlowController endpoints."""
        return PaymentFlowController(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 basic_auth_credentials=None, config=None):
        """Initialize a new instance of ModerntreasuryClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            basic_auth_credentials=basic_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseController.user_agent(),
                BaseController.user_agent_parameters())

        self.auth_managers = {
            "basic_auth": BasicAuth(self.config.basic_auth_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            ModerntreasuryClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
